-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library
-- CLI. Its format is tied to the specific database it was run against,
-- and it may not be correct for all databases. Use the CLI's build 
-- option to derive the best SQL for your dataset.

-- ###########################################################

CREATE TABLE opioid__search_rules_descriptions AS 
    SELECT 
        e.tty1,
        e.rela,
        e.tty2,
        e.rule,
        e.include,
        u1.tty_str AS tty1_str,
        u2.tty_str AS tty2_str
    FROM
        opioid__umls_tty as u1,
        opioid__umls_tty as u2,
        opioid__search_rules as e
    WHERE
        u1.tty = e.tty1
        AND u2.tty = e.tty2

-- ###########################################################

CREATE OR REPLACE VIEW opioid__acep_potential_rules AS
SELECT
    s.rxcui AS rxcui1,
    r.rxcui AS rxcui2,
    s.tty AS tty1,
    r.tty AS tty2,
    s.rui,
    s.rel,
    s.rela,
    s.str AS str1,
    r.str AS str2,
    r.keyword
FROM opioid__all_rxnconso_keywords AS r,
    opioid__acep_rela AS s
WHERE
    s.rxcui2 = r.rxcui
    AND s.rxcui2 NOT IN (SELECT DISTINCT RXCUI FROM opioid__acep_rxnconso_keywords)

-- ###########################################################

CREATE OR REPLACE VIEW opioid__acep_included_rels AS
SELECT
    r.rxcui1,
    r.rxcui2,
    r.tty1,
    r.tty2,
    r.rui,
    r.rel,
    r.rela,
    r.str1,
    r.str2,
    r.keyword
FROM opioid__acep_potential_rules AS r,
    opioid__search_rules AS e
WHERE
    r.REL NOT IN ('RB', 'PAR')
    AND e.include = TRUE
    AND r.TTY1 = e.TTY1
    AND r.TTY2 = e.TTY2
    AND r.RELA = e.RELA

-- ###########################################################

CREATE OR REPLACE VIEW opioid__acep_included_keywords AS
SELECT
    r.rxcui1,
    r.rxcui2,
    r.tty1,
    r.tty2,
    r.rui,
    r.rel,
    r.rela,
    r.str1,
    r.str2,
    r.keyword
FROM opioid__acep_potential_rules AS r
WHERE
    r.REL NOT IN ('RB', 'PAR')
    AND length(r.keyword) >= 4


-- ###########################################################

CREATE TABLE opioid__acep_combined_ruleset AS
SELECT
rxcui1,
rxcui2,
tty1,
tty2,
rui,
rel,
rela,
str1,
str2,
keyword
FROM opioid__acep_included_keywords
UNION
SELECT
rxcui1,
rxcui2,
tty1,
tty2,
rui,
rel,
rela,
str1,
str2,
keyword
FROM opioid__acep_included_rels

