-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library
-- CLI. Its format is tied to the specific database it was run against,
-- and it may not be correct for all databases. Use the CLI's build 
-- option to derive the best SQL for your dataset.

-- ###########################################################

CREATE TABLE opioid__acep_excluded_rules AS 
SELECT 
    rxcui1,
    rxcui2,
    tty1,
    tty2,
    rui,
    rel,
    rela,
    str1,
    str2,
    keyword
FROM
    opioid__acep_potential_rules
WHERE rui NOT IN (SELECT DISTINCT rui from opioid__acep_combined_ruleset)
AND rxcui1 NOT IN (SELECT DISTINCT rxcui1 from opioid__acep_combined_ruleset)   
AND rxcui2 NOT IN (SELECT DISTINCT rxcui2 from opioid__acep_combined_ruleset)

-- ###########################################################

CREATE VIEW opioid__acep_excluded_tradename AS 
SELECT 
    rxcui1,
    tty1,
    rel,
    rela,
    rxcui2,
    tty2,
    str2
FROM
    opioid__acep_excluded_rules
WHERE rela IN ('has_tradename','tradename_of')

-- ###########################################################

CREATE VIEW opioid__acep_excluded_consists AS 
SELECT 
    rxcui1,
    tty1,
    rel,
    rela,
    rxcui2,
    tty2,
    str2
FROM
    opioid__acep_excluded_rules
WHERE rela IN ('consists_of','constitutes')

-- ###########################################################

CREATE VIEW opioid__acep_excluded_is_a AS 
SELECT 
    rxcui1,
    tty1,
    rel,
    rela,
    rxcui2,
    tty2,
    str2
FROM
    opioid__acep_excluded_rules
WHERE rela IN ('isa','inverse_isa')

-- ###########################################################

CREATE VIEW opioid__acep_excluded_ingredient AS 
SELECT 
    rxcui1,
    tty1,
    rel,
    rela,
    rxcui2,
    tty2,
    str2
FROM
    opioid__acep_excluded_rules
WHERE rela IN ('has_ingredient','ingredient_of','has_precise_ingredient','precise_ingredient_of','has_ingredients','ingredients_of')

-- ###########################################################

CREATE VIEW opioid__acep_excluded_dose_form AS 
SELECT 
    rxcui1,
    tty1,
    rel,
    rela,
    rxcui2,
    tty2,
    str2
FROM
    opioid__acep_excluded_rules
WHERE rela IN ('dose_form_of','has_dose_form','doseformgroup_of','has_doseformgroup')

-- ###########################################################

CREATE VIEW opioid__acep_excluded_refresh AS 
SELECT 
    rxcui1,
    tty1,
    rel,
    rela,
    rxcui2,
    tty2,
    str2
FROM
    opioid__acep_excluded_rules
WHERE rela IN ('form_of','has_form')

-- ###########################################################

CREATE VIEW opioid__acep_excluded_form AS 
SELECT 
    rxcui1,
    tty1,
    rel,
    rela,
    rxcui2,
    tty2,
    str2
FROM
    opioid__acep_excluded_rules
WHERE rela IN ('form_of','has_form')

-- ###########################################################

CREATE VIEW opioid__acep_excluded_other AS 
SELECT 
    rxcui1,
    tty1,
    rel,
    rela,
    rxcui2,
    tty2,
    str2
FROM
    opioid__acep_excluded_rules
WHERE rela NOT IN ('has_tradename','tradename_of','consists_of','constitutes','isa','inverse_isa','has_ingredient','ingredient_of','has_precise_ingredient','precise_ingredient_of','has_ingredients','ingredients_of','dose_form_of','has_dose_form','doseformgroup_of','has_doseformgroup','form_of','has_form')
