-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library
-- CLI. Its format is tied to the specific database it was run against,
-- and it may not be correct for all databases. Use the CLI's build 
-- option to derive the best SQL for your dataset.

-- ###########################################################

CREATE TABLE opioid__all_rxnconso_keywords AS
WITH union_block AS (
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'vi q' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)vi q.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'a-cof' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)a-cof.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'actiq' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)actiq.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'allay' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)allay.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'arymo' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)arymo.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'c-cof' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)c-cof.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'codar' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)codar.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'evzio' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)evzio.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hycet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hycet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hytan' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hytan.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'm-oxy' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)m-oxy.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'nalex' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)nalex.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'norco' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)norco.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'oncet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)oncet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'qdolo' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)qdolo.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'revia' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)revia.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'rybix' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)rybix.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'vitiz' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)vitiz.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'vopac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)vopac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'xodol' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)xodol.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'xolox' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)xolox.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'ascomp' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)ascomp.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'avinza' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)avinza.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'azdone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)azdone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'bancap' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)bancap.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'codrix' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)codrix.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'conzip' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)conzip.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'depade' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)depade.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'duocet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)duocet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'dvorah' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)dvorah.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'embeda' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)embeda.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'entuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)entuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'exalgo' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)exalgo.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'exlago' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)exlago.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'gua hc' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)gua hc.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'heroin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)heroin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hyphed' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hyphed.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'kadian' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)kadian.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'kg-fed' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)kg-fed.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'kgs hc' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)kgs hc.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'kgs-hc' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)kgs-hc.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'lorcet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)lorcet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'lortab' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)lortab.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'narcan' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)narcan.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'narcof' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)narcof.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'narvox' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)narvox.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'norcet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)norcet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'notuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)notuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'nubain' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)nubain.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'oxaydo' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)oxaydo.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'oxecta' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)oxecta.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'pancof' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)pancof.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'panlor' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)panlor.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'procet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)procet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'procof' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)procof.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'prolex' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)prolex.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'rezira' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)rezira.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'ryna c' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)ryna c.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'ryna-c' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)ryna-c.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'ryzolt' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)ryzolt.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'stadol' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)stadol.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'subsys' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)subsys.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'symtan' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)symtan.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'talwin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)talwin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'trezix' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)trezix.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tussar' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tussar.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'z tuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)z tuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zolvit' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zolvit.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'abstral' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)abstral.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'ambenyl' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)ambenyl.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'anexsia' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)anexsia.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'atuss g' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)atuss g.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'belbuca' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)belbuca.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'brontex' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)brontex.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'butrans' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)butrans.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'codafed' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)codafed.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'codafen' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)codafen.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'codeine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)codeine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'cotab a' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)cotab a.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'cycofed' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)cycofed.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'dazidox' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)dazidox.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'demerol' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)demerol.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'depodur' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)depodur.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'diskets' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)diskets.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'dolacet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)dolacet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'duohist' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)duohist.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'endocet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)endocet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'endodan' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)endodan.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'fentora' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)fentora.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'flutuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)flutuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'fortral' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)fortral.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'genecof' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)genecof.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'guai-co' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)guai-co.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hy-phen' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hy-phen.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hycodan' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hycodan.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hycomed' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hycomed.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hycosin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hycosin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hycotab' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hycotab.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'ibudone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)ibudone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'kg-tuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)kg-tuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'kwelcof' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)kwelcof.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'lazanda' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)lazanda.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'm-clear' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)m-clear.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'm-eslon' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)m-eslon.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'mar-cof' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)mar-cof.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'maxifed' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)maxifed.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'megamor' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)megamor.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'monte-g' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)monte-g.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'nalocet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)nalocet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'novasus' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)novasus.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'nucofed' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)nucofed.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'nucynta' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)nucynta.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'obredon' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)obredon.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'oxydose' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)oxydose.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'oxyfast' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)oxyfast.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'oxynorm' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)oxynorm.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'panacet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)panacet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'panasal' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)panasal.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'perloxx' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)perloxx.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'primlev' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)primlev.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'prolate' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)prolate.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'romilar' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)romilar.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'roxanol' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)roxanol.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'roxicet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)roxicet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'roxilox' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)roxilox.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'su-tuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)su-tuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'subutex' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)subutex.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'sufenta' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)sufenta.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    't-gesic' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)t-gesic.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tl-hist' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tl-hist.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tramake' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tramake.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tussend' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tussend.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tuxarin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tuxarin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'vanacet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)vanacet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'vendone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)vendone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'vicodin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)vicodin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zamadol' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zamadol.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zamicet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zamicet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zohydro' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zohydro.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zomorph' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zomorph.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zotex c' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zotex c.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zotex-c' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zotex-c.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zubsolv' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zubsolv.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'allfen c' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)allfen c.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'allfen-c' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)allfen-c.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'amtussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)amtussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'atuss ex' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)atuss ex.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'atuss hd' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)atuss hd.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'atuss hs' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)atuss hs.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'atuss hx' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)atuss hx.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'atuss mr' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)atuss mr.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'atuss ms' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)atuss ms.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'bunavail' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)bunavail.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'buprenex' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)buprenex.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'co-gesic' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)co-gesic.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'codehist' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)codehist.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'codotuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)codotuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'combunox' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)combunox.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'condasin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)condasin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'contrave' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)contrave.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'cotuss v' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)cotuss v.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'cotuss-v' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)cotuss-v.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'de-chlor' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)de-chlor.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'deconsal' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)deconsal.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'dilaudid' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)dilaudid.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'dromoran' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)dromoran.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'fentanyl' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)fentanyl.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'gencofed' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)gencofed.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hyco-pap' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hyco-pap.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hycoclar' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hycoclar.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hycotuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hycotuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydrocet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydrocet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydrocod' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydrocod.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydrocof' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydrocof.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hysingla' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hysingla.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hytussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hytussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'kloxxado' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)kloxxado.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'liquicet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)liquicet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'maxidone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)maxidone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'maxiphen' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)maxiphen.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'medcodin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)medcodin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'medent c' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)medent c.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'medent-c' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)medent-c.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'medipain' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)medipain.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'morphine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)morphine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'morphone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)morphone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'ms cotin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)ms cotin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'mscontin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)mscontin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'mycodone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)mycodone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'naloxone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)naloxone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'novadyne' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)novadyne.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'novagest' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)novagest.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'nucodine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)nucodine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'nucotuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)nucotuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'onsollis' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)onsollis.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'oramorph' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)oramorph.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'oxyrapid' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)oxyrapid.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'percocet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)percocet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'percodan' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)percodan.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'primalev' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)primalev.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'recuvyra' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)recuvyra.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'roxiprin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)roxiprin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'roxybond' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)roxybond.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'sevredol' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)sevredol.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'spantuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)spantuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'suboxone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)suboxone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'synalgos' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)synalgos.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'taxadone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)taxadone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tramadol' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tramadol.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tryodone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tryodone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tussadur' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tussadur.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tussicap' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tussicap.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tussigon' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tussigon.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tuzistra' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tuzistra.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'ultracet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)ultracet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'vicotuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)vicotuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'vitussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)vitussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'vivitrol' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)vivitrol.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'welltuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)welltuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'xartemis' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)xartemis.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zotex hc' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zotex hc.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zotex-hc' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zotex-hc.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'baltussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)baltussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'bron tuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)bron tuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'bron-tuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)bron-tuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'brovex cb' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)brovex cb.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'brovex pb' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)brovex pb.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'brovex-cb' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)brovex-cb.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'brovex-pb' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)brovex-pb.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'canges xp' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)canges xp.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'ceta plus' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)ceta plus.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'co-tuss v' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)co-tuss v.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'co-tussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)co-tussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'codiclear' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)codiclear.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'damason-p' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)damason-p.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'dihistine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)dihistine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'dolagesic' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)dolagesic.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'dolophine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)dolophine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'duragesic' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)duragesic.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'duramorph' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)duramorph.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'duromorph' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)duromorph.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'genocidin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)genocidin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'guaifen c' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)guaifen c.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'guaifen-c' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)guaifen-c.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hycoclear' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hycoclear.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydro-pro' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydro-pro.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydromide' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydromide.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydron cp' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydron cp.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydron ex' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydron ex.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydropane' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydropane.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydrotuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydrotuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'infumorph' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)infumorph.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'maxi tuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)maxi tuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'megagesic' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)megagesic.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'meprozine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)meprozine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'merpergan' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)merpergan.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'methadone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)methadone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'methadose' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)methadose.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'ms contin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)ms contin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'nuco-tuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)nuco-tuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'numorphan' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)numorphan.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'oxycodone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)oxycodone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'oxycontin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)oxycontin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'percolone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)percolone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'pethidine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)pethidine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'pluratuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)pluratuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'polygesic' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)polygesic.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'reprexain' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)reprexain.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'rescudose' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)rescudose.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'ro-codone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)ro-codone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'sublocade' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)sublocade.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tramalgin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tramalgin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tussicare' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tussicare.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tussionex' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tussionex.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'verdrocet' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)verdrocet.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zodryl ac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zodryl ac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zodryl-ac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zodryl-ac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'a-g tussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)a-g tussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'astramorph' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)astramorph.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'bitex oral' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)bitex oral.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'co-histine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)co-histine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'codimal bn' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)codimal bn.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'codimal dh' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)codimal dh.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'codimal ph' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)codimal ph.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'cyclimorph' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)cyclimorph.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'despec-pdc' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)despec-pdc.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'dicomal-ph' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)dicomal-ph.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'duratuss h' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)duratuss h.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'endocodone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)endocodone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'guaifen ac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)guaifen ac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'guaifen-ac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)guaifen-ac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'halotussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)halotussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hexatussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hexatussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydro-tuss' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydro-tuss.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydrogesic' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydrogesic.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydron kgs' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydron kgs.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'idrocodone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)idrocodone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'levorfanol' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)levorfanol.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'lortuss ex' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)lortuss ex.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'lortuss-ex' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)lortuss-ex.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'lortuss hc' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)lortuss hc.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'lortuss-hc' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)lortuss-hc.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'meperidine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)meperidine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'morphabond' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)morphabond.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'morphinone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)morphinone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'nalbuphine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)nalbuphine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'naltrexone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)naltrexone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'p-v tussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)p-v tussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'p-v-tussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)p-v-tussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'pentazocin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)pentazocin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'physeptone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)physeptone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'probuphine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)probuphine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'propain hc' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)propain hc.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'q-v tussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)q-v tussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'roxicodone' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)roxicodone.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tapentadol' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tapentadol.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'tussiclear' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)tussiclear.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'vicoprofen' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)vicoprofen.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zodryl dac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zodryl dac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zodryl dec' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zodryl dec.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zodryl-dac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zodryl-dac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'zodryl-dec' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)zodryl-dec.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'butorphanol' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)butorphanol.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'carfentanil' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)carfentanil.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'codahistine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)codahistine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'decohistine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)decohistine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'decotuss hd' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)decotuss hd.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'decotuss-hd' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)decotuss-hd.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'duraganidin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)duraganidin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'dynatuss df' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)dynatuss df.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'dynatuss hc' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)dynatuss hc.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'guaifen dac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)guaifen dac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'guaifen-dac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)guaifen-dac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'guiatuss ac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)guiatuss ac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'levorphanol' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)levorphanol.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'merperidine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)merperidine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'novahistine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)novahistine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'penyazocine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)penyazocine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'poly tussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)poly tussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'poly-tussin' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)poly-tussin.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'relasin-hcx' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)relasin-hcx.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'stagesic-10' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)stagesic-10.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'stagesic 10' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)stagesic 10.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'sudatuss sf' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)sudatuss sf.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'vidone oral' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)vidone oral.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'vidone pill' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)vidone pill.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'dhc continus' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)dhc continus.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'duradyne dhc' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)duradyne dhc.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'guiatuss dac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)guiatuss dac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'hydrotropine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)hydrotropine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'margesic a-c' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)margesic a-c.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'poly-histine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)poly-histine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'statuss oral' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)statuss oral.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'buprenorphine' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)buprenorphine.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'donatussin dc' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)donatussin dc.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'nasatuss oral' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)nasatuss oral.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'cheratussin ac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)cheratussin ac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'donatussin max' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)donatussin max.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'cheratussin dac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)cheratussin dac.*$')
UNION
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    'guaiatussin dac' as keyword
FROM rxnorm.rxnconso AS a
WHERE regexp_like(a.str, '^.*(?i)guaiatussin dac.*$')

)

SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    b.keyword
FROM rxnorm.rxnconso AS a
LEFT JOIN union_block as b
ON a.rxcui= b.rxcui
AND a.str= b.str
AND a.tty= b.tty
AND a.sab= b.sab
AND a.code= b.code



-- ###########################################################

CREATE OR REPLACE VIEW opioid__acep_rxnconso AS
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code
FROM rxnorm.rxnconso AS a,
    opioid__acep_vsac AS b
WHERE
    a.rxcui = b.code

-- ###########################################################

CREATE OR REPLACE VIEW opioid__acep_rxnconso_keywords AS
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    a.code,
    b.str AS keyword
FROM opioid__acep_rxnconso AS a,
    opioid__keywords AS b
WHERE
    lower(a.str) LIKE concat('%',b.STR, '%')

-- ###########################################################

CREATE OR REPLACE VIEW opioid__acep_rxnsty AS
SELECT
    a.rxcui,
    a.tui,
    a.stn,
    a.sty,
    a.atui,
    a.cvf
FROM rxnorm.rxnsty AS a,
    opioid__acep_vsac AS b
WHERE
    a.rxcui = b.code

-- ###########################################################

CREATE OR REPLACE VIEW opioid__acep_rxnrel AS
SELECT
    a.rxcui1,
    a.rxaui1,
    a.stype1,
    a.rel,
    a.rxcui2,
    a.rxaui2,
    a.stype2,
    a.rela,
    a.rui,
    a.srui,
    a.sab,
    a.sl,
    a.rg
FROM rxnorm.rxnrel AS a,
    opioid__acep_vsac AS b
WHERE
    a.rxcui1 = b.code

-- ###########################################################

CREATE OR REPLACE VIEW opioid__acep_rela AS
SELECT
    a.rxcui,
    a.str,
    a.tty,
    a.sab,
    b.rxcui2,
    b.rel,
    b.rela,
    b.rui
FROM opioid__acep_rxnconso_keywords AS a,
    opioid__acep_RXNREL AS b
WHERE
    a.rxcui = b.rxcui1
