-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library
-- CLI. Its format is tied to the specific database it was run against,
-- and it may not be correct for all databases. Use the CLI's build 
-- option to derive the best SQL for your dataset.

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `cumulus_mhg_dev_db`.`opioid__keywords` (
    STR STRING
)
STORED AS PARQUET
LOCATION 's3://bucket/db_path/opioid/keywords.filtered'
tblproperties ("parquet.compression"="SNAPPY");

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `cumulus_mhg_dev_db`.`opioid__search_rules` (
    TTY1 STRING,
    RELA STRING,
    TTY2 STRING,
    rule STRING,
    include BOOLEAN
)
STORED AS PARQUET
LOCATION 's3://bucket/db_path/opioid/expand_rules'
tblproperties ("parquet.compression"="SNAPPY");

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `cumulus_mhg_dev_db`.`opioid__umls_tty` (
    TTY STRING,
    TTY_STR STRING
)
STORED AS PARQUET
LOCATION 's3://bucket/db_path/opioid/umls_tty'
tblproperties ("parquet.compression"="SNAPPY");
