-- noqa: disable=all
-- This sql was autogenerated as a reference example using the library
-- CLI. Its format is tied to the specific database it was run against,
-- and it may not be correct for all databases. Use the CLI's build 
-- option to derive the best SQL for your dataset.

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `cumulus_mhg_dev_db`.`opioid__keywords` (
    STR STRING
)
STORED AS PARQUET
LOCATION 's3://cumulus-athena-933137588087-us-east-1/results/cumulus_user_uploads/cumulus_mhg_dev_db/opioid/keywords.filtered'
tblproperties ("parquet.compression"="SNAPPY");

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `cumulus_mhg_dev_db`.`opioid__all_rxnconso_keywords` (
    RXCUI STRING,
    STR STRING,
    TTY STRING,
    SAB STRING,
    CODE STRING,
    keyword STRING,
    keyword_len STRING
)
STORED AS PARQUET
LOCATION 's3://cumulus-athena-933137588087-us-east-1/results/cumulus_user_uploads/cumulus_mhg_dev_db/opioid/all_rxcui_str.RXNCONSO_curated'
tblproperties ("parquet.compression"="SNAPPY");

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `cumulus_mhg_dev_db`.`opioid__search_rules` (
    TTY1 STRING,
    RELA STRING,
    TTY2 STRING,
    rule STRING,
    include BOOLEAN
)
STORED AS PARQUET
LOCATION 's3://cumulus-athena-933137588087-us-east-1/results/cumulus_user_uploads/cumulus_mhg_dev_db/opioid/expand_rules'
tblproperties ("parquet.compression"="SNAPPY");

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `cumulus_mhg_dev_db`.`opioid__umls_tty` (
    TTY STRING,
    TTY_STR STRING
)
STORED AS PARQUET
LOCATION 's3://cumulus-athena-933137588087-us-east-1/results/cumulus_user_uploads/cumulus_mhg_dev_db/opioid/umls_tty'
tblproperties ("parquet.compression"="SNAPPY");

-- ###########################################################

CREATE EXTERNAL TABLE IF NOT EXISTS `cumulus_mhg_dev_db`.`opioid__acep_vsac` (
    code STRING,
    display STRING
)
STORED AS PARQUET
LOCATION 's3://cumulus-athena-933137588087-us-east-1/results/cumulus_user_uploads/cumulus_mhg_dev_db/opioid/acep'
tblproperties ("parquet.compression"="SNAPPY");
