create or replace view opioid__define_dx_icd10 as select * from (values
('http://hl7.org/fhir/sid/icd-10-cm', 'F11.92', 'Opioid use, unspecified with intoxication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.920', 'Opioid use, unspecified with intoxication, uncomplicated')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.921', 'Opioid use, unspecified with intoxication delirium')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.922', 'Opioid use, unspecified with intoxication with perceptual disturbance')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.929', 'Opioid use, unspecified with intoxication, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.12', 'Opioid abuse with intoxication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.120', 'Opioid abuse with intoxication, uncomplicated')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.121', 'Opioid abuse with intoxication delirium')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.122', 'Opioid abuse with intoxication with perceptual disturbance')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.129', 'Opioid abuse with intoxication, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.22', 'Opioid dependence with intoxication')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.220', 'Opioid dependence with intoxication, uncomplicated')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.221', 'Opioid dependence with intoxication delirium')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.222', 'Opioid dependence with intoxication with perceptual disturbance')
,('http://hl7.org/fhir/sid/icd-10-cm', 'F11.229', 'Opioid dependence with intoxication, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.X1', 'Poisoning by opium, accidental (unintentional)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X1A', 'Poisoning by opium, accidental (unintentional), init encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X1D', 'Poisoning by opium, accidental (unintentional), subs encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X1S', 'Poisoning by opium, accidental (unintentional), sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.OX2', 'Poisoning by opium, intentional self-harm')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X2A', 'Poisoning by opium, intentional self-harm, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X2D', 'Poisoning by opium, intentional self-harm, subs encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X2S', 'Poisoning by opium, intentional self-harm, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X3', 'Poisoning by opium, assault')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X3A', 'Poisoning by opium, assault, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X3D', 'Poisoning by opium, assault, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X3S', 'Poisoning by opium, assault, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X4', 'Poisoning by opium, undetermined')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X4A', 'Poisoning by opium, undetermined, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X4D', 'Poisoning by opium, undetermined, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.0X4S', 'Poisoning by opium, undetermined, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X1', 'Poisoning by heroin, accidental (unintentional)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X1A', 'Poisoning by heroin, accidental (unintentional), init encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X1D', 'Poisoning by heroin, accidental (unintentional), subs encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X1S', 'Poisoning by heroin, accidental (unintentional), sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X2', 'Poisoning by heroin, intentional self-harm')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X2A', 'Poisoning by heroin, intentional self-harm, init encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X2D', 'Poisoning by heroin, intentional self-harm, subs encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X2S', 'Poisoning by heroin, intentional self-harm, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X3', 'Poisoning by heroin, assault')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X3A', 'Poisoning by heroin, assault, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X3D', 'Poisoning by heroin, assault, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X3S', 'Poisoning by heroin, assault, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X4', 'Poisoning by heroin, undetermined')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X4A', 'Poisoning by heroin, undetermined, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X4D', 'Poisoning by heroin, undetermined, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.1X4S', 'Poisoning by heroin, undetermined, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X1', 'Poisoning by oth opioids, accidental (unintentional)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X1A', 'Poisoning by oth opioids, accidental (unintentional), init')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X1D', 'Poisoning by oth opioids, accidental (unintentional), subs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X1S', 'Poisoning by oth opioids, accidental (unintentional), sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X2', 'Poisoning by oth opioids, intentional self-harm')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X2A', 'Poisoning by oth opioids, intentional self-harm, init encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X2D', 'Poisoning by oth opioids, intentional self-harm, subs encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X2S', 'Poisoning by oth opioids, intentional self-harm, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X3', 'Poisoning by other opioids, assault')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X3A', 'Poisoning by other opioids, assault, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X3D', 'Poisoning by other opioids, assault, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X3S', 'Poisoning by other opioids, assault, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.X4', 'Poisoning by other opioids, undetermined')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X4A', 'Poisoning by other opioids, undetermined, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X4D', 'Poisoning by other opioids, undetermined, subs encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.2X4S', 'Poisoning by other opioids, undetermined, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X1', 'Poisoning by methadone, accidental (unintentional)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X1A', 'Poisoning by methadone, accidental (unintentional), init')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X1D', 'Poisoning by methadone, accidental (unintentional), subs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X1S', 'Poisoning by methadone, accidental (unintentional), sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X2', 'Poisoning by methadone, intentional self-harm')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X2A', 'Poisoning by methadone, intentional self-harm, init encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X2D', 'Poisoning by methadone, intentional self-harm, subs encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X2S', 'Poisoning by methadone, intentional self-harm, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X3', 'Poisoning by methadone, assault')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X3A', 'Poisoning by methadone, assault, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X3D', 'Poisoning by methadone, assault, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X3S', 'Poisoning by methadone, assault')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X4', 'Poisoning by methadone, undetermined')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X4A', 'Poisoning by methadone, undetermined, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X4D', 'Poisoning by methadone, undetermined, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.3X4S', 'Poisoning by methadone, undetermined, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X1', 'Poisoning by oth synthetic narcotics')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X1A', 'Poisoning by oth synthetic narcotics, accidental, init')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X1D', 'Poisoning by oth synthetic narcotics, accidental, subs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X1S', 'Poisoning by oth synthetic narcotics, accidental, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X2', 'Poisoning by oth synthetic narcotics, self-harm')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X2A', 'Poisoning by oth synthetic narcotics, self-harm, init')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X2D', 'Poisoning by oth synthetic narcotics, self-harm, subs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X2S', 'Poisoning by oth synthetic narcotics, self-harm, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X3', 'Poisoning by other synthetic narcotics, assault')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X3A', 'Poisoning by other synthetic narcotics, assault, init encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X3D', 'Poisoning by other synthetic narcotics, assault, subs encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X3S', 'Poisoning by other synthetic narcotics, assault, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X4', 'Poisoning by oth synthetic narcotics, undetermined')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X4A', 'Poisoning by oth synthetic narcotics, undetermined, init')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X4D', 'Poisoning by oth synthetic narcotics, undetermined, subs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.4X4S', 'Poisoning by oth synthetic narcotics, undetermined, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.601', 'Poisoning by unsp narcotics, accidental')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.601A', 'Poisoning by unsp narcotics, accidental, init')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.601D', 'Poisoning by unsp narcotics, accidental, subs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.601S', 'Poisoning by unsp narcotics, accidental, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.602', 'Poisoning by unsp narcotics, intentional self-harm')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.602A', 'Poisoning by unsp narcotics, intentional self-harm, init')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.602D', 'Poisoning by unsp narcotics, intentional self-harm, subs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.602S', 'Poisoning by unsp narcotics, intentional self-harm')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.603', 'Poisoning by unspecified narcotics, assault')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.603A', 'Poisoning by unspecified narcotics, assault, init encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.603D', 'Poisoning by unspecified narcotics, assault, subs encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.603S', 'Poisoning by unspecified narcotics, assault, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.604', 'Poisoning by unsp narcotics, undetermined')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.604A', 'Poisoning by unsp narcotics, undetermined, init encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.604D', 'Poisoning by unsp narcotics, undetermined, subs encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.604S', 'Poisoning by unsp narcotics, undetermined, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.691', 'Poisoning by oth narcotics, accidental (unintentional)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.691A', 'Poisoning by oth narcotics, accidental (unintentional), init')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.691D', 'Poisoning by oth narcotics, accidental (unintentional), subs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.691S', 'Poisoning by oth narcotics, accidental (unintentional), sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.692', 'Poisoning by oth narcotics, intentional self-harm')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.692A', 'Poisoning by oth narcotics, intentional self-harm, init')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.692D', 'Poisoning by oth narcotics, intentional self-harm, subs')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.692S', 'Poisoning by oth narcotics, intentional self-harm, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.693', 'Poisoning by other narcotics, assault')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.693A', 'Poisoning by other narcotics, assault, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.693D', 'Poisoning by other narcotics, assault, subsequent encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.693S', 'Poisoning by other narcotics, assault, sequela')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.694', 'Poisoning by other narcotics, undetermined')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.694A', 'Poisoning by other narcotics, undetermined, init encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.694D', 'Poisoning by other narcotics, undetermined, subs encntr')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T40.694S', 'Poisoning by other narcotics, undetermined, sequela')
) AS t (system, code, display) ;