create or replace view opioid__define_rx as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '1819', 'Buprenorphine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '352364', 'Buprenorphine/Naloxone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203841', 'Buprenorphine Hydrochloride')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1729358', 'Buprenorphine inj (injection)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371161', 'Buprenorphine SL tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1295269', 'Buprenorphine TD')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2670', 'Codeine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '817579', 'Acetaminophen / Codeine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214444', 'Codeine / Promethazine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1008110', 'Codeine / Diclofenac')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214442', 'Codeine / Guaifenesin')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '689561', 'Acetaminophen / Butalbital / Caffeine / Codeine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '689563', 'Acetaminophen / Butalbital / Codeine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214449', 'Codeine / Phenylephrine / Promethazine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '91104', 'Codeine Sulfate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2672', 'Codeine Phosphate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1115966', 'Codeine Hydrochloride')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371613', 'Codeine Tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '371609', 'Codeine Inj (Injectable)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', ' 1155183', 'Codeine Inj (Injectable)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370754', 'Codeine/Acetaminophen tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1155597', 'Codeine/Acetaminophen liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', ' 370751', 'Codeine/Acetaminophen liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '4337', 'Fentanyl')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '142436', 'Fentanyl Citrate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1652097', 'Fentanyl Hydrochloride')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1735002', 'Fentanyl Injection (Im/Iv)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1294794', 'Fentanyl Transdermal')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1294774', 'Fentanyl Transmucosal Lozenge')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '668362', 'Fentanyl Disintegrating Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1294974', 'Fentanyl Sl Spray')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1159058', 'Fentanyl Citrate Transmucosal')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1159057', 'Fentanyl Citrate Nasal')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '858086', 'Fentanyl Citrate Buccal (Sl Film)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '3304', 'Heroin')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '5489', 'Hydrocodone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214182', 'Acetaminophin/Hydrocodone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214253', 'Aspirin / Hydrocodone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214627', 'Hydrocodone/Ibuprofen')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '142439', 'Hydrocodone Bitartrate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '236931', 'Hydrocodone Hydrochloride')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '221107', 'Hydrocodone Polisterix')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370641', 'Hydrocodone/Acetaminophen tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1151548', 'Hydrocodone/Acetaminophen liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', ' 370759', 'Hydrocodone/Acetaminophen liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370676', 'Hydrocodone/Ibuprofen tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '3423', 'Hydromorphone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1007561', 'Atropine / Hydromorphone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214594', 'Guaifenesin / Hydromorphone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203177', 'Hydromorphone Hydrochloride')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '370654', 'Hydromorphone Tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1164619', 'Hydromorphone Liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', ' 370653', 'Hydromorphone Liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1724207', 'Hydromorphone INJ (Injection)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '902728', 'Hydromorphone ER (Extended Release)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '6378', 'Levorphanol')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '153973', 'Levorphanol Tartrate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372593', 'Levorphanol Tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1163479', 'Levorphanol INJ (Injectable)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '6754', 'Meperidine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214699', 'Meperidine / Promethazine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '689788', 'Acetaminophen / Meperidine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '689609', 'Atropine / Meperidine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '103755', 'Meperidine Hydrochloride')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372766', 'Meperidine Tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1160384', 'Meperidine Liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', ' 60800', 'Meperidine Liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1665037', 'Meperidine INJ (Injection)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '6813', 'Methadone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '218337', 'Methadone Hydrochloride')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372808', 'Methadone Tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1161620', 'Methadone Liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', ' 372806', 'Methadone Liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1161619', 'Methadone INJ (Injectable)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', ' 372807', 'Methadone INJ (Injectable)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '7052', 'Morphine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '866331', 'Morphine / Naltrexone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '689610', 'Atropine / Morphine')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '30236', 'Morphine Sulfate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '477397', 'Morphine Sulfate Liposomal')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '235774', 'Morphine Tartrate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372959', 'Morphine IR (Immediate Release)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156362', 'Morphine Liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', ' 106841', 'Morphine Liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1728776', 'Morphine INJ (Injection)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372957', 'Morphine Suppository (Rectal)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372960', 'Morphine CR (Continuous Release)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '7804', 'Oxycodone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214183', 'Oxycodone/Acetaminophen')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '214256', 'Oxycodone/Aspirin')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '484259', 'Ibuprofen / Oxycodone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1545902', 'Naloxone / Oxycodone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1806700', 'Naltrexone / Oxycodone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '82063', 'Oxycodone Hydrochloride')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '159821', 'Oxycodone Terephthalate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373198', 'Oxycodone Tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373195', 'Oxycodone Cap')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1161681', 'Oxycodone Liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', ' 373196', 'Oxycodone Liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '373200', 'Oxycodone/ Acetaminophen Tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '375581', 'Oxycodone/ Acetaminophen Cap')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1151889', 'Oxycodone/ Acetaminophen Liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', ' 373199', 'Oxycodone/ Acetaminophen Liquid')
,('http://www.nlm.nih.gov/research/umls/rxnorm', 'nan', 'Oxycodone Cr')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '385094', 'Oxycodone Er')
,('http://www.nlm.nih.gov/research/umls/rxnorm', ' 1790526', 'Oxycodone Er')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1491831', 'Oxycodone/ Acetaminophen ER tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '7814', 'OXYMORPHONE')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '82064', 'Oxymorphone Hydrochloride')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1809679', 'Oxymorphone INJ (injection)')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643113', 'Oxymorphone IR')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '643115', 'Oxymorphone CR')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '10689', 'Tramadol')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '352362', 'Tramadol/Acetaminophen')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '82110', 'Tramadol Hydrochloride')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '374173', 'Tramadol Tab')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '374174', 'Tramadol CR')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '7242', 'Naloxone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '7243', 'Naltrexone')
) AS t (system, code, display) ;