create or replace view opioid__define_rx_naloxone as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '1010598', 'naloxone hydrochloride dihydrate')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1156980', 'naloxone Injectable Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191212', 'naloxone hydrochloride 0.02 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191221', 'naloxone hydrochloride 0.4 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191222', 'naloxone hydrochloride 0.4 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191227', 'naloxone hydrochloride 1 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191228', 'naloxone hydrochloride 1 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191234', '1 ML naloxone hydrochloride 0.4 MG/ML Cartridge')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1191250', '2 ML naloxone hydrochloride 1 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1307055', 'naloxone 1 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1307060', 'naloxone 3 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431075', 'naloxone 0.36 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1431100', 'naloxone 1.4 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1495293', '0.4 ML naloxone hydrochloride 1 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1495294', 'Evzio')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1495295', 'naloxone hydrochloride 1 MG/ML [Evzio]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1495298', '0.4 ML naloxone hydrochloride 1 MG/ML Auto-Injector [Evzio]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1542387', 'naloxone 0.3 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1544850', 'naloxone 0.7 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1597567', 'naloxone 2.9 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1597572', 'naloxone 2.1 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1659888', 'naloxone Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1659890', 'naloxone Auto-Injector [Evzio]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1659913', 'naloxone Cartridge')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1659928', 'naloxone Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1659929', '1 ML naloxone hydrochloride 0.4 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1666337', 'naloxone 0.71 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1725055', 'naloxone hydrochloride 40 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1725056', 'naloxone Inhalant Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1725057', 'naloxone Nasal Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1725058', 'naloxone Nasal Spray')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1725059', 'naloxone hydrochloride 40 MG/ML Nasal Spray')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1725060', 'naloxone hydrochloride 40 MG/ML [Narcan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1725061', 'naloxone Nasal Spray [Narcan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1725062', 'Narcan Inhalant Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1725063', 'Narcan Nasal Product')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1725064', 'naloxone hydrochloride 40 MG/ML Nasal Spray [Narcan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1855729', 'naloxone hydrochloride 5 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1855730', '0.4 ML naloxone hydrochloride 5 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1855731', 'naloxone hydrochloride 5 MG/ML [Evzio]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1855732', '0.4 ML naloxone hydrochloride 5 MG/ML Auto-Injector [Evzio]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1864411', 'naloxone 0.18 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870932', 'naloxone hydrochloride 20 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870933', 'naloxone hydrochloride 20 MG/ML Nasal Spray')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870934', 'naloxone hydrochloride 20 MG/ML [Narcan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1870935', 'naloxone hydrochloride 20 MG/ML Nasal Spray [Narcan]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '197117', 'Narcan')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '199059', 'nalmefene 1 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '203192', 'naloxone hydrochloride')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2540702', 'naloxone hydrochloride 80 MG/ML')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2540703', 'naloxone hydrochloride 80 MG/ML Nasal Spray')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2540704', 'Kloxxado')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2540705', 'naloxone hydrochloride 80 MG/ML [Kloxxado]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2540706', 'naloxone Nasal Spray [Kloxxado]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2540709', 'naloxone hydrochloride 80 MG/ML Nasal Spray [Kloxxado]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589612', '0.5 ML naloxone hydrochloride 10 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2589618', '0.5 ML naloxone hydrochloride 10 MG/ML Prefilled Syringe [Zimhi]')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2592953', '2 ML nalmefene 1 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '2596175', '0.4 ML naloxone hydrochloride 25 MG/ML Auto-Injector')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '343216', 'naloxone 0.5 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '353392', 'naloxone 2 MG')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '372989', 'naloxone Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '7242', 'naloxone')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '727348', 'naloxone Prefilled Syringe')
) AS t (system, code, display) ;