create or replace view opioid__define_rx_buprenorphine as select * from (values
('http://www.nlm.nih.gov/research/umls/rxnorm', '1432969', '168 HR Buprenorphine 0.015 MG/HR Transdermal System')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1488634', 'Buprenorphine hydrochloride 1.3 MG/ML Injectable Suspension')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1542997', '168 HR Buprenorphine 0.0075 MG/HR Transdermal System')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1594650', 'Buprenorphine 1.8 MG/ML Injectable Solution')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1655032', '1 ML Buprenorphine 0.3 MG/ML Cartridge')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1716057', 'Buprenorphine 0.15 MG Buccal Film')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1716065', 'Buprenorphine 0.3 MG Buccal Film')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1716069', 'Buprenorphine 0.45 MG Buccal Film')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1716073', 'Buprenorphine 0.6 MG Buccal Film')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1716077', 'Buprenorphine 0.075 MG Buccal Film')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1716081', 'Buprenorphine 0.75 MG Buccal Film')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1716086', 'Buprenorphine 0.9 MG Buccal Film')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1797650', 'Buprenorphine 74.2 MG Drug Implant')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1996184', '0.5 ML Buprenorphine 200 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '1996192', '1.5 ML Buprenorphine 200 MG/ML Prefilled Syringe')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '238129', '1 ML Buprenorphine 0.3 MG/ML Injection')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '246474', 'Buprenorphine 0.2 MG Sublingual Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '250426', 'Buprenorphine 0.4 MG Sublingual Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351264', 'Buprenorphine 2 MG Sublingual Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '351265', 'Buprenorphine 8 MG Sublingual Tablet')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '388506', '72 HR Buprenorphine 0.07 MG/HR Transdermal System')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '388507', '72 HR Buprenorphine 0.0525 MG/HR Transdermal System')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '388508', '72 HR Buprenorphine 0.035 MG/HR Transdermal System')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '904870', '168 HR Buprenorphine 0.01 MG/HR Transdermal System')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '904876', '168 HR Buprenorphine 0.02 MG/HR Transdermal System')
,('http://www.nlm.nih.gov/research/umls/rxnorm', '904880', '168 HR Buprenorphine 0.005 MG/HR Transdermal System')
) AS t (system, code, display) ;