create or replace view opioid__define_lab as select * from (values
('http://loinc.org', '16248-7', '6-monoacetylmorphine free [Mass/volume] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '18343-4', '6-Monoacetylmorphine (6-MAM) [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '19321-9', '6-Monoacetylmorphine (6-MAM) [Presence] in Urine by Screen method')
,('http://loinc.org', '19322-7', '6-Monoacetylmorphine (6-MAM) [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '19323-5', '6-Monoacetylmorphine (6-MAM) cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '19324-3', '6-Monoacetylmorphine (6-MAM) cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '19593-3', '6-Monoacetylmorphine (6-MAM) [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '43184-1', '6-Monoacetylmorphine (6-MAM) [Presence] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '47004-7', '6-monoacetylmorphine free [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '70197-9', '6-Monoacetylmorphine (6-MAM) [Moles/volume] in Urine by Confirmatory method')
,('http://loinc.org', '72763-6', '6-Monoacetylmorphine (6-MAM) [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '74677-6', '6-Monoacetylmorphine (6-MAM) [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '77755-7', '6-Monoacetylmorphine (6-MAM) cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '78759-8', '6-Monoacetylmorphine (6-MAM) [Presence] in Blood by Screen method')
,('http://loinc.org', '78760-6', '6-Monoacetylmorphine (6-MAM) [Presence] in Body fluid by Screen method')
,('http://loinc.org', '80115-9', '6-Monoacetylmorphine (6-MAM) [Mass/volume] in Blood by Confirmatory method')
,('http://loinc.org', '80116-7', '6-Monoacetylmorphine (6-MAM) [Mass/volume] in Body fluid by Confirmatory method')
,('http://loinc.org', '87816-5', '6-Monoacetylmorphine (6-MAM) [Presence] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '58359-1', 'Buprenorphine+Norbuprenorphine [Presence] in Urine by Screen method')
,('http://loinc.org', '79139-2', 'Buprenorphine [Presence] in Blood by Screen method')
,('http://loinc.org', '82372-4', 'Buprenorphine [Presence] in Gastric fluid by Screen method')
,('http://loinc.org', '77205-3', 'Buprenorphine [Presence] in Meconium by Screen method')
,('http://loinc.org', '73942-5', 'Buprenorphine [Presence] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '82369-0', 'Buprenorphine [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '82373-2', 'Buprenorphine [Presence] in Unspecified specimen by Screen method')
,('http://loinc.org', '77787-0', 'Buprenorphine cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '91027-3', 'Buprenorphine-3-glucuronide [Presence] in Urine by Screen method')
,('http://loinc.org', '77201-2', 'Buprenorphine+Norbuprenorphine [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '72762-8', 'Buprenorphine [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '53846-2', 'Buprenorphine [Mass/volume] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '49752-9', 'Buprenorphine [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '75367-3', 'Buprenorphine [Mass/mass] in Meconium by Confirmatory method')
,('http://loinc.org', '79138-4', 'Buprenorphine [Presence] in Blood by Confirmatory method')
,('http://loinc.org', '77204-6', 'Buprenorphine [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '16208-1', 'Buprenorphine [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '78811-7', 'Buprenorphine cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '77764-9', 'Buprenorphine cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '89321-4', 'Buprenorphine-3-glucuronide [Mass/volume] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '82370-8', 'Norbuprenorphine [Presence] in Gastric fluid by Screen method')
,('http://loinc.org', '82374-0', 'Norbuprenorphine [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '82371-6', 'Norbuprenorphine [Presence] in Urine by Screen method')
,('http://loinc.org', '82375-7', 'Norbuprenorphine [Presence] in Unspecified specimen by Screen method')
,('http://loinc.org', '89305-7', 'Norbuprenorphine-3-glucuronide [Presence] in Urine by Screen method')
,('http://loinc.org', '72746-1', 'Norbuprenorphine [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '53880-1', 'Norbuprenorphine [Mass/volume] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '49751-1', 'Norbuprenorphine [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '75379-8', 'Norbuprenorphine [Mass/mass] in Meconium by Confirmatory method')
,('http://loinc.org', '77206-1', 'Norbuprenorphine [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '66131-4', 'Norbuprenorphine [Presence] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '58362-5', 'Norbuprenorphine [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '78866-1', 'Norbuprenorphine cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '77774-8', 'Norbuprenorphine cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '89322-2', 'Norbuprenorphine-3-glucuronide [Mass/volume] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '19411-8', 'Codeine [Presence] in Urine by Screen method')
,('http://loinc.org', '19413-4', 'Codeine cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '46262-2', 'Codeine Free [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '89310-7', 'Codeine-6-glucuronide [Presence] in Urine by Screen method')
,('http://loinc.org', '72759-4', 'Codeine [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '86226-8', 'Codeine [Mass/volume] in Serum, Plasma or Blood by Confirmatory method')
,('http://loinc.org', '16250-3', 'Codeine [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '68542-0', 'Codeine [Mass/mass] in Meconium by Confirmatory method')
,('http://loinc.org', '74675-0', 'Codeine [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '16197-6', 'Codeine [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '13641-6', 'Codeine [Presence] in Urine by SAMHSA confirm method')
,('http://loinc.org', '70206-8', 'Codeine [Moles/volume] in Urine by Confirmatory method')
,('http://loinc.org', '77767-2', 'Codeine cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '19414-2', 'Codeine cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '16644-7', 'Codeine Free [Presence] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '19439-9', 'Diamorphine [Presence] in Urine by Screen method')
,('http://loinc.org', '19441-5', 'Diamorphine cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '16756-9', 'Diamorphine [Mass/volume] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '16755-1', 'Diamorphine [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '16198-4', 'Diamorphine [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '19442-3', 'Diamorphine cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '46257-2', 'Dihydrocodeine+Hydrocodol [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '19446-4', 'Dihydrocodeine [Presence] in Urine by Screen method')
,('http://loinc.org', '19450-6', 'Dihydrocodeine cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '46704-3', 'Dihydrocodeine Free+Hydrocodol Free [Mass/volume] in Serum or Plasma by Screen method')
,('http://loinc.org', '46703-5', 'Dihydrocodeine Free+Hydrocodol Free [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '74811-1', 'Dihydrocodeine [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '86227-6', 'Dihydrocodeine [Mass/volume] in Serum, Plasma or Blood by Confirmatory method')
,('http://loinc.org', '19448-0', 'Dihydrocodeine [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '16211-5', 'Dihydrocodeine [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '19451-4', 'Dihydrocodeine cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '16775-9', 'Dihydrocodeine Free [Presence] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '15401-3', 'Drugs identified in Blood by Screen method')
,('http://loinc.org', '34601-5', 'Drugs identified in Body fluid')
,('http://loinc.org', '12287-9', 'Drugs identified in Gastric fluid by Screen method')
,('http://loinc.org', '27034-8', 'Drugs identified in Hair by Screen method')
,('http://loinc.org', '64126-6', 'Drugs identified in Meconium by Confirmatory method')
,('http://loinc.org', '32797-3', 'Drugs identified in Meconium by Screen method')
,('http://loinc.org', '42326-9', 'Drugs identified in Mothers milk by Screen method')
,('http://loinc.org', '20785-2', 'Drugs identified in Serum or Plasma by Screen method')
,('http://loinc.org', '27208-8', 'Drugs identified in Stool by Screen method')
,('http://loinc.org', '20786-0', 'Drugs identified in Tissue by Screen method')
,('http://loinc.org', '16793-2', 'Drugs identified in Unknown substance by Screen method')
,('http://loinc.org', '41270-0', 'Drugs identified in Urine')
,('http://loinc.org', '40464-0', 'Drugs identified in Urine by Confirmatory method')
,('http://loinc.org', '12286-1', 'Drugs identified in Urine by Screen method')
,('http://loinc.org', '12289-5', 'Drugs identified in Vitreous fluid by Screen method')
,('http://loinc.org', '40585-2', 'Drugs identified in Unspecified specimen by Confirmatory method')
,('http://loinc.org', '20787-8', 'Drugs identified in Unspecified specimen by Screen method')
,('http://loinc.org', '51782-1', 'Drugs of abuse 7 and Alcohol and Tricyclics panel - Urine by Screen method')
,('http://loinc.org', '24349-3', 'Drugs of abuse 5 panel - Urine')
,('http://loinc.org', '65750-2', 'Drugs of abuse 5 panel - Urine by Screen method')
,('http://loinc.org', '72479-9', 'Drugs of abuse panel - Blood by Screen method')
,('http://loinc.org', '91054-7', 'Drugs of abuse panel - Body fluid')
,('http://loinc.org', '91056-2', 'Drugs of abuse panel - Hair')
,('http://loinc.org', '49046-6', 'Drugs of abuse panel - Meconium')
,('http://loinc.org', '91055-4', 'Drugs of abuse panel - Tissue')
,('http://loinc.org', '69739-1', 'Drugs of abuse panel - Urine by Screen method')
,('http://loinc.org', '87428-9', 'Drugs of abuse screen W Reflex confirm panel - Urine')
,('http://loinc.org', '58738-6', 'Drugs of abuse [Interpretation] in Meconium')
,('http://loinc.org', '58379-9', 'Fentanyl+Norfentanyl [Presence] in Urine by Screen method')
,('http://loinc.org', '73936-7', 'Fentanyl [Presence] in Blood by Screen method')
,('http://loinc.org', '87815-7', 'Fentanyl [Presence] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '59673-4', 'Fentanyl [Presence] in Urine by Screen method')
,('http://loinc.org', '79260-6', 'Fentanyl cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '66130-6', 'Fentanyl+Norfentanyl [Presence] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '66129-8', 'Fentanyl+Norfentanyl [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '74810-3', 'Acetyl fentanyl [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '73938-3', 'Fentanyl [Mass/volume] in Blood by Confirmatory method')
,('http://loinc.org', '72760-2', 'Fentanyl [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '74136-3', 'Fentanyl [Mass/volume] in Serum, Plasma or Blood by Confirmatory method')
,('http://loinc.org', '58381-5', 'Fentanyl [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '40839-3', 'Fentanyl [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '78827-3', 'Fentanyl cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '79259-8', 'Fentanyl cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '66129-8', 'Fentanyl+Norfentanyl [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '86223-5', 'Acetyl norfentanyl [Mass/volume] in Serum, Plasma or Blood by Confirmatory method')
,('http://loinc.org', '73937-5', 'Norfentanyl [Mass/volume] in Blood by Confirmatory method')
,('http://loinc.org', '72745-3', 'Norfentanyl [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '74137-1', 'Norfentanyl [Mass/volume] in Serum, Plasma or Blood by Confirmatory method')
,('http://loinc.org', '58383-1', 'Norfentanyl [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '43200-5', 'Norfentanyl [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '78867-9', 'Norfentanyl cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '77775-5', 'Norfentanyl cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '19482-9', 'Hydrocodone [Presence] in Urine by Screen method')
,('http://loinc.org', '19484-5', 'Hydrocodone cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '74760-0', 'Hydrocodone and metabolites panel - Urine by Confirmatory method')
,('http://loinc.org', '72753-7', 'Hydrocodone [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '86229-2', 'Hydrocodone [Mass/volume] in Serum, Plasma or Blood by Confirmatory method')
,('http://loinc.org', '16252-9', 'Hydrocodone [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '68544-6', 'Hydrocodone [Mass/mass] in Meconium by Confirmatory method')
,('http://loinc.org', '74644-6', 'Hydrocodone [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '19483-7', 'Hydrocodone [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '79261-4', 'Hydrocodone cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '19485-2', 'Hydrocodone cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '19486-0', 'Hydromorphone [Presence] in Urine by Screen method')
,('http://loinc.org', '19487-8', 'Hydromorphone cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '46260-6', 'Hydromorphone Free [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '89309-9', 'Hydromorphone-3-glucuronide [Presence] in Urine by Screen method')
,('http://loinc.org', '72733-9', 'Hydromorphone [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '86230-0', 'Hydromorphone [Mass/volume] in Serum, Plasma or Blood by Confirmatory method')
,('http://loinc.org', '16998-7', 'Hydromorphone [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '68541-2', 'Hydromorphone [Mass/mass] in Meconium by Confirmatory method')
,('http://loinc.org', '74645-3', 'Hydromorphone [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '18473-9', 'Hydromorphone [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '77770-6', 'Hydromorphone cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '19488-6', 'Hydromorphone cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '46971-8', 'Hydromorphone Free [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '19516-4', 'Levorphanol [Presence] in Urine by Screen method')
,('http://loinc.org', '19518-0', 'Levorphanol cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '20540-1', 'Levorphanol [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '16213-1', 'Levorphanol [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '19519-8', 'Levorphanol cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '51984-3', 'Meperidine+Normeperidine [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '58385-6', 'Meperidine+Normeperidine [Presence] in Urine by Screen method')
,('http://loinc.org', '35617-0', 'Meperidine [Mass/volume] in Serum or Plasma by Screen method')
,('http://loinc.org', '74108-2', 'Meperidine [Presence] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '87497-4', 'Meperidine [Presence] in Serum, Plasma or Blood by Screen method')
,('http://loinc.org', '19532-1', 'Meperidine [Presence] in Urine by Screen method')
,('http://loinc.org', '19534-7', 'Meperidine cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '72384-1', 'Meperidine+Normeperidine [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '72749-5', 'Meperidine [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '16253-7', 'Meperidine [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '16207-3', 'Meperidine [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '19535-4', 'Meperidine cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '91039-8', 'Methadone+Metabolite [Presence] in Body fluid by Screen method')
,('http://loinc.org', '91046-3', 'Methadone+Metabolite [Presence] in Hair by Screen method')
,('http://loinc.org', '91030-7', 'Methadone+Metabolite [Presence] in Meconium by Screen method')
,('http://loinc.org', '91033-1', 'Methadone+Metabolite [Presence] in Serum, Plasma or Blood by Screen method')
,('http://loinc.org', '91050-5', 'Methadone+Metabolite [Presence] in Tissue by Screen method')
,('http://loinc.org', '42251-9', 'Methadone+Metabolite [Presence] in Urine by Screen method')
,('http://loinc.org', '70148-2', 'Methadone [Presence] in Urine by Screen method >150 ng/mL')
,('http://loinc.org', '70149-0', 'Methadone [Presence] in Urine by Screen method >300 ng/mL')
,('http://loinc.org', '72734-7', 'Methadone [Mass/volume] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '35618-8', 'Methadone [Mass/volume] in Serum or Plasma by Screen method')
,('http://loinc.org', '70147-4', 'Methadone [Mass/volume] in Urine by Screen method')
,('http://loinc.org', '72400-5', 'Methadone [Presence] in Blood by Screen method')
,('http://loinc.org', '72626-5', 'Methadone [Presence] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '59705-4', 'Methadone [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '19550-3', 'Methadone [Presence] in Urine by Screen method')
,('http://loinc.org', '19552-9', 'Methadone cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '73661-1', 'Methadone panel - Saliva (oral fluid) by Screen method')
,('http://loinc.org', '72475-7', 'Methadone+Metabolite [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '45022-1', 'Methadone+Metabolite [Presence] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '72388-2', 'Methadone [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '16246-1', 'Methadone [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '48956-7', 'Methadone [Mass/volume] in Unspecified specimen by Confirmatory method')
,('http://loinc.org', '72387-4', 'Methadone [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '47411-4', 'Methadone [Presence] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '16199-2', 'Methadone [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '79249-9', 'Methadone cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '19553-7', 'Methadone cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '72476-5', 'Methadone panel - Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '19599-0', 'Morphine cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '46259-8', 'Morphine Free [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '19601-4', 'Morphine Free [Presence] in Urine by Screen method')
,('http://loinc.org', '19603-0', 'Morphine Free cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '89308-1', 'Morphine-6-Glucuronide [Presence] in Urine by Screen method')
,('http://loinc.org', '72752-9', 'Morphine [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '16251-1', 'Morphine [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '69027-1', 'Morphine [Mass/mass] in Meconium by Confirmatory method')
,('http://loinc.org', '74654-5', 'Morphine [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '17290-8', 'Morphine [Presence] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '16196-8', 'Morphine [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '13648-1', 'Morphine [Presence] in Urine by SAMHSA confirm method')
,('http://loinc.org', '70210-0', 'Morphine [Moles/volume] in Urine by Confirmatory method')
,('http://loinc.org', '77773-0', 'Morphine cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '19600-6', 'Morphine cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '20550-0', 'Morphine Free [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '19602-2', 'Morphine Free [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '19604-8', 'Morphine Free cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '91039-8', 'Methadone+Metabolite [Presence] in Body fluid by Screen method')
,('http://loinc.org', '91046-3', 'Methadone+Metabolite [Presence] in Hair by Screen method')
,('http://loinc.org', '91030-7', 'Methadone+Metabolite [Presence] in Meconium by Screen method')
,('http://loinc.org', '91033-1', 'Methadone+Metabolite [Presence] in Serum, Plasma or Blood by Screen method')
,('http://loinc.org', '91050-5', 'Methadone+Metabolite [Presence] in Tissue by Screen method')
,('http://loinc.org', '42251-9', 'Methadone+Metabolite [Presence] in Urine by Screen method')
,('http://loinc.org', '70148-2', 'Methadone [Presence] in Urine by Screen method >150 ng/mL')
,('http://loinc.org', '70149-0', 'Methadone [Presence] in Urine by Screen method >300 ng/mL')
,('http://loinc.org', '72734-7', 'Methadone [Mass/volume] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '35618-8', 'Methadone [Mass/volume] in Serum or Plasma by Screen method')
,('http://loinc.org', '70147-4', 'Methadone [Mass/volume] in Urine by Screen method')
,('http://loinc.org', '72400-5', 'Methadone [Presence] in Blood by Screen method')
,('http://loinc.org', '72626-5', 'Methadone [Presence] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '59705-4', 'Methadone [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '19550-3', 'Methadone [Presence] in Urine by Screen method')
,('http://loinc.org', '19552-9', 'Methadone cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '73661-1', 'Methadone panel - Saliva (oral fluid) by Screen method')
,('http://loinc.org', '72475-7', 'Methadone+Metabolite [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '45022-1', 'Methadone+Metabolite [Presence] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '72388-2', 'Methadone [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '16246-1', 'Methadone [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '48956-7', 'Methadone [Mass/volume] in Unspecified specimen by Confirmatory method')
,('http://loinc.org', '72387-4', 'Methadone [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '47411-4', 'Methadone [Presence] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '16199-2', 'Methadone [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '79249-9', 'Methadone cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '19553-7', 'Methadone cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '72476-5', 'Methadone panel - Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '72730-5', 'Mitragynine/Creatinine [Mass Ratio] in Urine')
,('http://loinc.org', '75649-4', 'Mitragynine+7-Hydroxymitragynine [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '72732-1', 'Mitragynine [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '73995-3', 'Mitragynine [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '19597-4', 'Morphine [Presence] in Urine by Screen method')
,('http://loinc.org', '42618-9', 'Naloxone [Presence] in Urine by Screen method')
,('http://loinc.org', '89307-3', 'Naloxone-3-glucuronide [Presence] in Urine by Screen method')
,('http://loinc.org', '87807-4', 'Naloxone [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '77207-9', 'Naloxone [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '78864-6', 'Naloxone cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '87822-3', 'Naltrexone [Presence] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '19609-7', 'Naltrexone [Presence] in Urine by Screen method')
,('http://loinc.org', '19612-1', 'Naltrexone cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '87823-1', 'Naltrexone [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '19610-5', 'Naltrexone [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '18334-3', 'Naltrexone [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '19613-9', 'Naltrexone cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '31088-8', 'Narcotics and opioids [Identifier] in Bile fluid')
,('http://loinc.org', '29376-1', 'Narcotics and opioids [Identifier] in Blood')
,('http://loinc.org', '29377-9', 'Narcotics and opioids [Identifier] in Gastric fluid')
,('http://loinc.org', '12554-2', 'Narcotics and opioids [Identifier] in Urine')
,('http://loinc.org', '21431-2', 'Opiates [Presence] in Urine by Screen method >2000 ng/mL')
,('http://loinc.org', '70151-6', 'Opiates [Presence] in Urine by Screen method >300 ng/mL')
,('http://loinc.org', '74167-8', 'Opiates [Mass/volume] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '70150-8', 'Opiates [Mass/volume] in Urine by Screen method')
,('http://loinc.org', '26744-3', 'Opiates [Mass/mass] in Meconium by Screen method')
,('http://loinc.org', '51691-4', 'Opiates [Presence] in Blood by Screen method')
,('http://loinc.org', '91043-0', 'Opiates [Presence] in Body fluid by Screen method')
,('http://loinc.org', '8212-3', 'Opiates [Presence] in Gastric fluid by Screen method')
,('http://loinc.org', '40805-4', 'Opiates [Presence] in Hair by Screen method')
,('http://loinc.org', '8216-4', 'Opiates [Presence] in Meconium by Screen method')
,('http://loinc.org', '40806-2', 'Opiates [Presence] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '8219-8', 'Opiates [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '91052-1', 'Opiates [Presence] in Tissue by Screen method')
,('http://loinc.org', '8226-3', 'Opiates [Presence] in Unknown substance by Screen method')
,('http://loinc.org', '8222-2', 'Opiates [Presence] in Urine by SAMHSA screen method')
,('http://loinc.org', '19295-5', 'Opiates [Presence] in Urine by Screen method')
,('http://loinc.org', '19299-7', 'Opiates cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '19297-1', 'Opiates tested for in Urine by Screen method Narrative')
,('http://loinc.org', '19296-3', 'Opiates tested for in Urine by Screen method Nominal')
,('http://loinc.org', '17384-9', 'Opiates [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '8211-5', 'Opiates [Presence] in Gastric fluid by Confirmatory method')
,('http://loinc.org', '8215-6', 'Opiates [Presence] in Meconium by Confirmatory method')
,('http://loinc.org', '74656-0', 'Opiates [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '8218-0', 'Opiates [Presence] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '8225-5', 'Opiates [Presence] in Unknown substance by Confirmatory method')
,('http://loinc.org', '18390-5', 'Opiates [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '8221-4', 'Opiates [Presence] in Urine by SAMHSA confirm method')
,('http://loinc.org', '19300-3', 'Opiates cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '50620-4', 'Opiates cutoff [Mass/mass] in Meconium for Confirmatory method')
,('http://loinc.org', '69026-3', 'Opiates panel - Meconium by Confirmatory method')
,('http://loinc.org', '19298-9', 'Opiates positive [Identifier] in Urine by Confirmatory method')
,('http://loinc.org', '19642-8', 'Oxycodone [Presence] in Urine by Screen method')
,('http://loinc.org', '19644-4', 'Oxycodone cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '19646-9', 'Oxymorphone [Presence] in Urine by Screen method')
,('http://loinc.org', '19649-3', 'Oxymorphone cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '46256-4', 'Oxycodone Free [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '46258-0', 'Oxymorphone Free [Presence] in Serum or Plasma by Screen method')
,('http://loinc.org', '50021-5', 'Oxycodone [Mass/volume] in Serum, Plasma or Blood by Screen method')
,('http://loinc.org', '58430-0', 'Oxycodone+Oxymorphone [Presence] in Urine by Screen method')
,('http://loinc.org', '60276-3', 'Oxycodone+Oxymorphone cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '60276-3', 'Oxycodone+Oxymorphone cutoff [Mass/volume] in Urine for Screen method')
,('http://loinc.org', '69356-4', 'Oxycodone [Presence] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '71430-3', 'Oxycodone+Oxymorphone [Presence] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '72402-1', 'Oxycodone [Presence] in Blood by Screen method')
,('http://loinc.org', '72751-1', 'Oxycodone [Mass/volume] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '73996-1', 'Oxycodone [Presence] in Meconium by Screen method')
,('http://loinc.org', '77732-6', 'Oxycodone+Oxymorphone [Presence] in Serum, Plasma or Blood by Screen method')
,('http://loinc.org', '89301-6', 'Oxymorphone-3-glucuronide [Presence] in Urine by Screen method')
,('http://loinc.org', '91032-3', 'Oxycodone+Oxymorphone [Presence] in Meconium by Screen method')
,('http://loinc.org', '91044-8', 'Oxycodone+Oxymorphone [Presence] in Body fluid by Screen method')
,('http://loinc.org', '91053-9', 'Oxycodone+Oxymorphone [Presence] in Tissue by Screen method')
,('http://loinc.org', '16249-5', 'Oxycodone [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '17395-5', 'Oxymorphone [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '18325-1', 'Oxymorphone [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '19643-6', 'Oxycodone [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '19645-1', 'Oxycodone cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '19650-1', 'Oxymorphone cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '46973-4', 'Oxycodone Free [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '46974-2', 'Oxymorphone Free [Mass/volume] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '46975-9', 'Oxymorphone Free [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '61197-0', 'Oxycodone+Oxymorphone [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '68543-8', 'Oxycodone [Mass/mass] in Meconium by Confirmatory method')
,('http://loinc.org', '69028-9', 'Oxymorphone [Mass/mass] in Meconium by Confirmatory method')
,('http://loinc.org', '70215-9', 'Oxycodone [Moles/volume] in Urine by Confirmatory method')
,('http://loinc.org', '72750-3', 'Oxycodone [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '72766-9', 'Oxymorphone [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '74657-8', 'Oxycodone [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '74658-6', 'Oxycodone+Oxymorphone [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '74658-6', 'Oxycodone+Oxymorphone [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '74659-4', 'Oxymorphone [Presence] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '77729-2', 'Oxymorphone [Mass/volume] in Serum, Plasma or Blood by Confirmatory method')
,('http://loinc.org', '77730-0', 'Oxycodone [Mass/volume] in Serum, Plasma or Blood by Confirmatory method')
,('http://loinc.org', '77731-8', 'Oxycodone+Oxymorphone [Interpretation] in Serum, Plasma or Blood Qualitative by Confirmatory method')
,('http://loinc.org', '77780-5', 'Oxymorphone cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '79255-6', 'Oxycodone cutoff [Mass/volume] in Saliva (oral fluid) for Confirmatory method')
,('http://loinc.org', '72740-4', 'traMADol [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '20561-7', 'traMADol [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '93720-1', 'traMADol [Mass/mass] in Meconium by Confirmatory method')
,('http://loinc.org', '79147-5', 'traMADol [Presence] in Blood by Confirmatory method')
,('http://loinc.org', '17718-8', 'traMADol [Presence] in Urine by Confirmatory method')
,('http://loinc.org', '19713-7', 'traMADol cutoff [Mass/volume] in Urine for Confirmatory method')
,('http://loinc.org', '72747-9', 'N-nortramadol [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '92904-2', 'N-nortramadol [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '93722-7', 'N-nortramadol [Mass/mass] in Meconium by Confirmatory method')
,('http://loinc.org', '87760-5', 'N-nortramadol/Creatinine [Mass Ratio] in Urine by Confirmatory method')
,('http://loinc.org', '72741-2', 'Nortramadol [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '18340-0', 'Nortramadol [Mass/volume] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '18339-2', 'Nortramadol [Presence] in Serum or Plasma by Confirmatory method')
,('http://loinc.org', '90750-1', 'O-nortramadol [Mass/volume] in Saliva (oral fluid) by Confirmatory method')
,('http://loinc.org', '82974-7', 'O-nortramadol [Mass/volume] in Serum, Plasma or Blood by Confirmatory method')
,('http://loinc.org', '92639-4', 'O-nortramadol [Mass/volume] in Urine by Confirmatory method')
,('http://loinc.org', '93721-9', 'O-nortramadol [Mass/mass] in Meconium by Confirmatory method')
,('http://loinc.org', '79148-3', 'traMADol [Presence] in Blood by Screen method')
,('http://loinc.org', '93719-3', 'traMADol [Presence] in Meconium by Screen method')
,('http://loinc.org', '74110-8', 'traMADol [Presence] in Saliva (oral fluid) by Screen method')
,('http://loinc.org', '19710-3', 'traMADol [Presence] in Urine by Screen method')
,('http://loinc.org', '19712-9', 'traMADol cutoff [Mass/volume] in Urine for Screen method')
) AS t (system, code, display) ;