create or replace view opioid__define_dx_sepsis as select * from (values
('http://snomed.info/sct', '10001005', 'Bacterial sepsis (disorder)')
,('http://snomed.info/sct', '1089000', 'Intrauterine sepsis of fetus (disorder)')
,('http://snomed.info/sct', '1092461000119104', 'Sepsis without acute organ dysfunction (disorder)')
,('http://snomed.info/sct', '1125006', 'Sepsis during labor (disorder)')
,('http://snomed.info/sct', '127751000119108', 'Sepsis caused by Staphylococcus without acute organ dysfunction (disorder)')
,('http://snomed.info/sct', '16751003', 'Acute tubulointerstitial nephritis associated with systemic infection (disorder)')
,('http://snomed.info/sct', '17732003', 'Ecthyma gangrenosum (disorder)')
,('http://snomed.info/sct', '186365005', 'Acute meningococcemia (disorder)')
,('http://snomed.info/sct', '18700001', 'Septicemia caused by Chromobacterium (disorder)')
,('http://snomed.info/sct', '194394004', 'Gram positive sepsis (disorder)')
,('http://snomed.info/sct', '196853004', 'Septicemic pasteurellosis (disorder)')
,('http://snomed.info/sct', '199710008', 'Sepsis during labor, delivered (disorder)')
,('http://snomed.info/sct', '199711007', 'Sepsis during labor with antenatal problem (disorder)')
,('http://snomed.info/sct', '200196001', 'Puerperal sepsis with postnatal complication (disorder)')
,('http://snomed.info/sct', '240385003', 'Septicemic glanders (disorder)')
,('http://snomed.info/sct', '240389009', 'Septicemic melioidosis (disorder)')
,('http://snomed.info/sct', '25042006', 'Tracheostomy sepsis (disorder)')
,('http://snomed.info/sct', '2858002', 'Puerperal sepsis (disorder)')
,('http://snomed.info/sct', '300985007', 'Coliform septicemia (disorder)')
,('http://snomed.info/sct', '300986008', 'Proteus septicemia (disorder)')
,('http://snomed.info/sct', '310649002', 'Vancomycin resistant enterococcal septicemia (disorder)')
,('http://snomed.info/sct', '310669007', 'Septicemia caused by enterococcus (disorder)')
,('http://snomed.info/sct', '313437008', 'Meningococcal meningitis with acute meningococcal septicemia (disorder)')
,('http://snomed.info/sct', '314130008', 'Meningococcal meningitis with meningococcal septicemia (disorder)')
,('http://snomed.info/sct', '32751000119100', 'Line sepsis associated with dialysis catheter (disorder)')
,('http://snomed.info/sct', '371044001', 'Transient respiratory distress with sepsis (disorder)')
,('http://snomed.info/sct', '402961006', 'Pseudomonas septicemia with skin involvement (disorder)')
,('http://snomed.info/sct', '4089001', 'Meningococcemia (disorder)')
,('http://snomed.info/sct', '41936006', 'Septicemia caused by Erysipelothrix insidiosa (disorder)')
,('http://snomed.info/sct', '42939002', 'Pyemia (disorder)')
,('http://snomed.info/sct', '436741000124105', 'Septicemia associated with vascular access catheter (disorder)')
,('http://snomed.info/sct', '436751000124107', 'Sepsis associated with internal vascular access (disorder)')
,('http://snomed.info/sct', '443980004', 'Neutropenic sepsis (disorder)')
,('http://snomed.info/sct', '447684006', 'Sepsis caused by Erysipelothrix (disorder)')
,('http://snomed.info/sct', '447685007', 'Sepsis caused by Haemophilus influenzae (disorder)')
,('http://snomed.info/sct', '447841007', 'Sepsis caused by Candida (disorder)')
,('http://snomed.info/sct', '447843005', 'Sepsis caused by anaerobic bacteria (disorder)')
,('http://snomed.info/sct', '447894003', 'Sepsis caused by Staphylococcus (disorder)')
,('http://snomed.info/sct', '447897005', 'Sepsis caused by Acinetobacter (disorder)')
,('http://snomed.info/sct', '447898000', 'Sepsis caused by Actinomyces (disorder)')
,('http://snomed.info/sct', '447899008', 'Sepsis caused by Escherichia coli (disorder)')
,('http://snomed.info/sct', '448417001', 'Sepsis caused by Staphylococcus aureus (disorder)')
,('http://snomed.info/sct', '448418006', 'Sepsis caused by Streptococcus (disorder)')
,('http://snomed.info/sct', '448419003', 'Sepsis caused by Streptococcus agalactiae (disorder)')
,('http://snomed.info/sct', '448420009', 'Sepsis caused by Streptococcus group D (disorder)')
,('http://snomed.info/sct', '448421008', 'Sepsis caused by Streptococcus pneumoniae (disorder)')
,('http://snomed.info/sct', '448422001', 'Sepsis caused by Streptococcus suis (disorder)')
,('http://snomed.info/sct', '448482003', 'Sepsis caused by Bacillus anthracis (disorder)')
,('http://snomed.info/sct', '448483008', 'Sepsis caused by Enterobacter (disorder)')
,('http://snomed.info/sct', '448812000', 'Sepsis caused by methicillin resistant Staphylococcus aureus (disorder)')
,('http://snomed.info/sct', '448813005', 'Sepsis caused by Pseudomonas (disorder)')
,('http://snomed.info/sct', '449082003', 'Sepsis caused by Gram negative bacteria (disorder)')
,('http://snomed.info/sct', '449083008', 'Sepsis caused by Salmonella (disorder)')
,('http://snomed.info/sct', '449084002', 'Sepsis caused by Serratia (disorder)')
,('http://snomed.info/sct', '449335002', 'Sepsis caused by Listeria monocytogenes (disorder)')
,('http://snomed.info/sct', '449504009', 'Sepsis caused by Streptococcus pyogenes (disorder)')
,('http://snomed.info/sct', '449505005', 'Sepsis caused by coagulase negative Staphylococcus (disorder)')
,('http://snomed.info/sct', '449546000', 'Sepsis caused by Haemophilus influenzae type B (disorder)')
,('http://snomed.info/sct', '51831006', 'Sepsis following infusion, injection, transfusion AND/OR vaccination (disorder)')
,('http://snomed.info/sct', '5567000', 'Gas gangrene septicemia (disorder)')
,('http://snomed.info/sct', '698819004', 'Postoperative sepsis (disorder)')
,('http://snomed.info/sct', '700050004', 'Overwhelming infection in asplenic patient (disorder)')
,('http://snomed.info/sct', '700051000', 'Sepsis in asplenic subject (disorder)')
,('http://snomed.info/sct', '700052007', 'Post-splenectomy sepsis (disorder)')
,('http://snomed.info/sct', '700053002', 'Sepsis associated with acquired immunodeficiency syndrome (disorder)')
,('http://snomed.info/sct', '700054008', 'Sepsis caused by fungus (disorder)')
,('http://snomed.info/sct', '700055009', 'Sepsis with cutaneous manifestations (disorder)')
,('http://snomed.info/sct', '707271004', 'Sepsis due to oral infection (disorder)')
,('http://snomed.info/sct', '713854001', 'Perinatal sepsis (disorder)')
,('http://snomed.info/sct', '713865006', 'Perinatal sepsis caused by Streptococcus agalactiae (disorder)')
,('http://snomed.info/sct', '713866007', 'Perinatal sepsis caused by Escherichia coli (disorder)')
,('http://snomed.info/sct', '714083007', 'Recurrent salmonella sepsis co-occurrent with human immunodeficiency virus infection (disorder)')
,('http://snomed.info/sct', '715070000', 'Sepsis caused by Peptostreptococcus (disorder)')
,('http://snomed.info/sct', '715071001', 'Sepsis caused by anaerobic streptococcus (disorder)')
,('http://snomed.info/sct', '721104000', 'Sepsis due to urinary tract infection (disorder)')
,('http://snomed.info/sct', '721572008', 'Sepsis caused by Pseudomonas aeruginosa (disorder)')
,('http://snomed.info/sct', '77206006', 'Puerperal pelvic sepsis (disorder)')
,('http://snomed.info/sct', '79587009', 'Septicemia caused by Bacteroides (disorder)')
,('http://snomed.info/sct', '9012003', 'Septicemic plague (disorder)')
,('http://snomed.info/sct', '91302008', 'Sepsis (disorder)')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A32.7', 'Listerial sepsis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A40.0', 'Sepsis due to streptococcus, group A')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A40.1', 'Sepsis due to streptococcus, group B')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A40.3', 'Sepsis due to Streptococcus pneumoniae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A40.8', 'Other streptococcal sepsis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A40.9', 'Streptococcal sepsis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.01', 'Sepsis due to Methicillin susceptible Staphylococcus aureus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.02', 'Sepsis due to Methicillin resistant Staphylococcus aureus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.1', 'Sepsis due to other specified staphylococcus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.2', 'Sepsis due to unspecified staphylococcus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.3', 'Sepsis due to Hemophilus influenzae')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.4', 'Sepsis due to anaerobes')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.50', 'Gram-negative sepsis, unspecified')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.51', 'Sepsis due to Escherichia coli [E. coli]')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.52', 'Sepsis due to Pseudomonas')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.53', 'Sepsis due to Serratia')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.59', 'Other Gram-negative sepsis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.81', 'Sepsis due to Enterococcus')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.89', 'Other specified sepsis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'A41.9', 'Sepsis, unspecified organism')
,('http://hl7.org/fhir/sid/icd-10-cm', 'I76', 'Septic arterial embolism')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O85', 'Puerperal sepsis')
,('http://hl7.org/fhir/sid/icd-10-cm', 'O86.04', 'Sepsis following an obstetrical procedure')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R65.20', 'Severe sepsis without septic shock')
,('http://hl7.org/fhir/sid/icd-10-cm', 'R65.21', 'Severe sepsis with septic shock')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T81.12XA', 'Postprocedural septic shock, initial encounter')
,('http://hl7.org/fhir/sid/icd-10-cm', 'T81.44XA', 'Sepsis following a procedure, initial encounter')
) AS t (system, code, display) ;