create or replace view opioid__define_dx_sud as select * from (values
('http://snomed.info/sct', '10028000', 'Uncomplicated sedative, hypnotic AND/OR anxiolytic withdrawal (disorder)')
,('http://snomed.info/sct', '10327003', 'Cocaine-induced mood disorder (disorder)')
,('http://snomed.info/sct', '10741871000119101', 'Alcohol dependence in pregnancy (disorder)')
,('http://snomed.info/sct', '10755041000119100', 'Alcohol dependence in childbirth (disorder)')
,('http://snomed.info/sct', '1081000119105', 'Opioid dependence, on agonist therapy (disorder)')
,('http://snomed.info/sct', '11047881000119101', 'Cannabis hyperemesis syndrome co-occurrent and due to cannabis abuse (disorder)')
,('http://snomed.info/sct', '11048011000119103', 'Cannabis hyperemesis syndrome co-occurrent and due to cannabis dependence (disorder)')
,('http://snomed.info/sct', '11387009', 'Organic mental disorder caused by psychoactive substance (disorder)')
,('http://snomed.info/sct', '1230071005', 'Amfetamine and/or amfetamine derivative abuse, episodic (disorder)')
,('http://snomed.info/sct', '1230072003', 'Amfetamine and/or amfetamine derivative abuse, continuous (disorder)')
,('http://snomed.info/sct', '1230084001', 'Nondependent psychostimulant abuse, continuous (disorder)')
,('http://snomed.info/sct', '1230085000', 'Nondependent amfetamine and/or amfetamine derivative, continuous (disorder)')
,('http://snomed.info/sct', '1230086004', 'Nondependent psychostimulant abuse, episodic (disorder)')
,('http://snomed.info/sct', '1230087008', 'Nondependent amfetamine and/or amfetamine derivative abuse, episodic (disorder)')
,('http://snomed.info/sct', '1230088003', 'Nondependent amfetamine and/or amfetamine derivative abuse (disorder)')
,('http://snomed.info/sct', '1230089006', 'Nondependent psychostimulant abuse (disorder)')
,('http://snomed.info/sct', '1231160001', 'Hypnotic dependence, episodic (disorder)')
,('http://snomed.info/sct', '1231162009', 'Hypnotic dependence, continuous (disorder)')
,('http://snomed.info/sct', '1231319004', 'Methylenedioxymethamphetamine dependence (disorder)')
,('http://snomed.info/sct', '1231327008', 'Amfetamine and/or amfetamine derivative dependence episodic (disorder)')
,('http://snomed.info/sct', '1231328003', 'Amfetamine and/or amfetamine derivative dependence continuous (disorder)')
,('http://snomed.info/sct', '1231333004', 'Psychostimulant dependence episodic (disorder)')
,('http://snomed.info/sct', '1231336007', 'Psychostimulant dependence continuous (disorder)')
,('http://snomed.info/sct', '12398281000119105', 'Methamphetamine withdrawal (disorder)')
,('http://snomed.info/sct', '12398651000119100', 'Sleep disorder caused by methamphetamine (disorder)')
,('http://snomed.info/sct', '125851000119106', 'Continuous sedative abuse (disorder)')
,('http://snomed.info/sct', '135301000119103', 'Parasomnia caused by alcohol (disorder)')
,('http://snomed.info/sct', '135311000119100', 'Insomnia caused by alcohol (disorder)')
,('http://snomed.info/sct', '135321000119107', 'Hypersomnia caused by alcohol (disorder)')
,('http://snomed.info/sct', '1383008', 'Hallucinogen mood disorder (disorder)')
,('http://snomed.info/sct', '144981000119109', 'Nondependent intraveous amphetamine abuse (disorder)')
,('http://snomed.info/sct', '145101000119102', 'Intravenous cocaine abuse (disorder)')
,('http://snomed.info/sct', '145121000119106', 'Intravenous nondependent opioid abuse (disorder)')
,('http://snomed.info/sct', '145841000119107', 'Episodic phencyclidine abuse (disorder)')
,('http://snomed.info/sct', '14784000', 'Organic mental disorder caused by opioid (disorder)')
,('http://snomed.info/sct', '15167005', 'Alcohol abuse (disorder)')
,('http://snomed.info/sct', '15277004', 'Hallucinogen-induced anxiety disorder (disorder)')
,('http://snomed.info/sct', '154211000119108', 'Chronic pancreatitis due to chronic alcoholism (disorder)')
,('http://snomed.info/sct', '1686006', 'Sedative, hypnotic AND/OR anxiolytic-induced anxiety disorder (disorder)')
,('http://snomed.info/sct', '18653004', 'Alcohol intoxication delirium (disorder)')
,('http://snomed.info/sct', '18689007', 'Inhalant intoxication delirium (disorder)')
,('http://snomed.info/sct', '191475009', 'Chronic alcoholic brain syndrome (disorder)')
,('http://snomed.info/sct', '191476005', 'Alcohol withdrawal hallucinosis (disorder)')
,('http://snomed.info/sct', '191478006', 'Alcoholic paranoia (disorder)')
,('http://snomed.info/sct', '191480000', 'Alcohol withdrawal syndrome (disorder)')
,('http://snomed.info/sct', '191802004', 'Acute alcoholic intoxication in alcoholism (disorder)')
,('http://snomed.info/sct', '191804003', 'Continuous acute alcoholic intoxication in alcoholism (disorder)')
,('http://snomed.info/sct', '191805002', 'Episodic acute alcoholic intoxication in alcoholism (disorder)')
,('http://snomed.info/sct', '191811004', 'Continuous chronic alcoholism (disorder)')
,('http://snomed.info/sct', '191812006', 'Episodic chronic alcoholism (disorder)')
,('http://snomed.info/sct', '191819002', 'Continuous opioid dependence (disorder)')
,('http://snomed.info/sct', '191820008', 'Episodic opioid dependence (disorder)')
,('http://snomed.info/sct', '191825003', 'Hypnotic or anxiolytic dependence, continuous (disorder)')
,('http://snomed.info/sct', '191826002', 'Hypnotic or anxiolytic dependence, episodic (disorder)')
,('http://snomed.info/sct', '191831000', 'Cocaine dependence, continuous (disorder)')
,('http://snomed.info/sct', '191832007', 'Cocaine dependence, episodic (disorder)')
,('http://snomed.info/sct', '191837001', 'Cannabis dependence, continuous (disorder)')
,('http://snomed.info/sct', '191838006', 'Cannabis dependence, episodic (disorder)')
,('http://snomed.info/sct', '191843004', 'Amphetamine or psychostimulant dependence, continuous (disorder)')
,('http://snomed.info/sct', '191844005', 'Amphetamine or psychostimulant dependence, episodic (disorder)')
,('http://snomed.info/sct', '191849000', 'Hallucinogen dependence, continuous (disorder)')
,('http://snomed.info/sct', '191850000', 'Hallucinogen dependence, episodic (disorder)')
,('http://snomed.info/sct', '191853003', 'Glue sniffing dependence (disorder)')
,('http://snomed.info/sct', '191855005', 'Glue sniffing dependence, continuous (disorder)')
,('http://snomed.info/sct', '191856006', 'Glue sniffing dependence, episodic (disorder)')
,('http://snomed.info/sct', '191865004', 'Combined opioid with non-opioid drug dependence (disorder)')
,('http://snomed.info/sct', '191867007', 'Combined opioid with non-opioid drug dependence, continuous (disorder)')
,('http://snomed.info/sct', '191868002', 'Combined opioid with non-opioid drug dependence, episodic (disorder)')
,('http://snomed.info/sct', '191882002', 'Nondependent alcohol abuse, continuous (disorder)')
,('http://snomed.info/sct', '191883007', 'Nondependent alcohol abuse, episodic (disorder)')
,('http://snomed.info/sct', '191891003', 'Nondependent cannabis abuse (disorder)')
,('http://snomed.info/sct', '191893000', 'Nondependent cannabis abuse, continuous (disorder)')
,('http://snomed.info/sct', '191894006', 'Nondependent cannabis abuse, episodic (disorder)')
,('http://snomed.info/sct', '191899001', 'Nondependent hallucinogen abuse, continuous (disorder)')
,('http://snomed.info/sct', '191900006', 'Nondependent hallucinogen abuse, episodic (disorder)')
,('http://snomed.info/sct', '191905001', 'Nondependent hypnotic or anxiolytic abuse, continuous (disorder)')
,('http://snomed.info/sct', '191906000', 'Nondependent hypnotic or anxiolytic abuse, episodic (disorder)')
,('http://snomed.info/sct', '191909007', 'Nondependent opioid abuse (disorder)')
,('http://snomed.info/sct', '191912005', 'Nondependent opioid abuse, continuous (disorder)')
,('http://snomed.info/sct', '191913000', 'Nondependent opioid abuse, episodic (disorder)')
,('http://snomed.info/sct', '191916008', 'Nondependent cocaine abuse (disorder)')
,('http://snomed.info/sct', '191918009', 'Nondependent cocaine abuse, continuous (disorder)')
,('http://snomed.info/sct', '191919001', 'Nondependent cocaine abuse, episodic (disorder)')
,('http://snomed.info/sct', '191924003', 'Nondependent amphetamine or psychostimulant abuse, continuous (disorder)')
,('http://snomed.info/sct', '191925002', 'Nondependent amphetamine or psychostimulant abuse, episodic (disorder)')
,('http://snomed.info/sct', '19445006', 'Opioid-induced psychotic disorder with hallucinations (disorder)')
,('http://snomed.info/sct', '1973000', 'Sedative, hypnotic AND/OR anxiolytic-induced psychotic disorder with delusions (disorder)')
,('http://snomed.info/sct', '20385005', 'Psychotic disorder with delusions caused by opioid (disorder)')
,('http://snomed.info/sct', '20876004', 'Inhalant-induced anxiety disorder (disorder)')
,('http://snomed.info/sct', '21647008', 'Amphetamine dependence (disorder)')
,('http://snomed.info/sct', '22574000', 'Cocaine-induced sleep disorder (disorder)')
,('http://snomed.info/sct', '230443000', 'Narcotic withdrawal epilepsy (disorder)')
,('http://snomed.info/sct', '231461004', 'Hypnotic or anxiolytic abuse (disorder)')
,('http://snomed.info/sct', '231462006', 'Barbiturate abuse (disorder)')
,('http://snomed.info/sct', '231468005', 'Lysergic acid diethylamide dependence (disorder)')
,('http://snomed.info/sct', '231469002', 'Mescaline dependence (disorder)')
,('http://snomed.info/sct', '231470001', 'Anxiolytic dependence (disorder)')
,('http://snomed.info/sct', '231472009', 'Barbiturate dependence (disorder)')
,('http://snomed.info/sct', '231473004', 'Benzodiazepine dependence (disorder)')
,('http://snomed.info/sct', '231474005', 'Diazepam dependence (disorder)')
,('http://snomed.info/sct', '231477003', 'Dependence on diamorphine (disorder)')
,('http://snomed.info/sct', '231478008', 'Methadone dependence (disorder)')
,('http://snomed.info/sct', '231479000', 'Morphine dependence (disorder)')
,('http://snomed.info/sct', '231480002', 'Opium dependence (disorder)')
,('http://snomed.info/sct', '23601000119102', 'Sedative withdrawal (disorder)')
,('http://snomed.info/sct', '2403008', 'Psychoactive substance dependence (disorder)')
,('http://snomed.info/sct', '25753007', 'Amphetamine-induced sleep disorder (disorder)')
,('http://snomed.info/sct', '26714005', 'Cannabis-induced psychotic disorder with hallucinations (disorder)')
,('http://snomed.info/sct', '268640002', 'Hypnotic or anxiolytic dependence (disorder)')
,('http://snomed.info/sct', '268645007', 'Nondependent alcohol abuse (disorder)')
,('http://snomed.info/sct', '268646008', 'Nondependent hallucinogen abuse (disorder)')
,('http://snomed.info/sct', '268647004', 'Nondependent hypnotic or anxiolytic abuse (disorder)')
,('http://snomed.info/sct', '268648009', 'Nondependent amphetamine or other psychostimulant abuse (disorder)')
,('http://snomed.info/sct', '275471001', 'Psychostimulant dependence (disorder)')
,('http://snomed.info/sct', '27956007', 'Cocaine intoxication (disorder)')
,('http://snomed.info/sct', '281004', 'Dementia associated with alcoholism (disorder)')
,('http://snomed.info/sct', '284591009', 'Persistent alcohol abuse (disorder)')
,('http://snomed.info/sct', '288021000119107', 'Disorder due to alcohol abuse (disorder)')
,('http://snomed.info/sct', '288031000119105', 'Alcohol induced disorder co-occurrent and due to alcohol dependence (disorder)')
,('http://snomed.info/sct', '288461000119105', 'Psychosis caused by inhalant (disorder)')
,('http://snomed.info/sct', '28864000', 'Sedative, hypnotic AND/OR anxiolytic-induced mood disorder (disorder)')
,('http://snomed.info/sct', '288851000119106', 'Opioid-induced mood disorder due to opioid abuse (disorder)')
,('http://snomed.info/sct', '288861000119108', 'Opioid-induced mood disorder due to opioid dependence (disorder)')
,('http://snomed.info/sct', '29212009', 'Organic mental disorder caused by ingestible alcohol (disorder)')
,('http://snomed.info/sct', '29733004', 'Mood disorder caused by opioid (disorder)')
,('http://snomed.info/sct', '301643003', 'Sedative, hypnotic AND/OR anxiolytic-induced persisting amnestic disorder (disorder)')
,('http://snomed.info/sct', '30491001', 'Cocaine delusional disorder (disorder)')
,('http://snomed.info/sct', '308742005', 'Alcohol withdrawal-induced convulsion (disorder)')
,('http://snomed.info/sct', '312098001', 'Sedative, hypnotic AND/OR anxiolytic-related disorder (disorder)')
,('http://snomed.info/sct', '312936002', 'Organic mental disorder caused by anxiolytic agent (disorder)')
,('http://snomed.info/sct', '31956009', 'Cocaine dependence (disorder)')
,('http://snomed.info/sct', '32009006', 'Hallucinogen hallucinosis (disorder)')
,('http://snomed.info/sct', '32358001', 'Amphetamine delusional disorder (disorder)')
,('http://snomed.info/sct', '32875003', 'Inhalant-induced persisting dementia (disorder)')
,('http://snomed.info/sct', '34111000119108', 'Nondependent amphetamine abuse (disorder)')
,('http://snomed.info/sct', '34938008', 'Anxiety disorder caused by alcohol (disorder)')
,('http://snomed.info/sct', '361151007', 'Delirium due to sedative withdrawal (disorder)')
,('http://snomed.info/sct', '37344009', 'Cannabis abuse (disorder)')
,('http://snomed.info/sct', '38247002', 'Hallucinogen dependence (disorder)')
,('http://snomed.info/sct', '39807006', 'Cannabis intoxication delirium (disorder)')
,('http://snomed.info/sct', '39951001', 'Cannabis-induced anxiety disorder (disorder)')
,('http://snomed.info/sct', '40571009', 'Hallucinogen intoxication delirium (disorder)')
,('http://snomed.info/sct', '41083005', 'Sleep disorder caused by ingestible alcohol (disorder)')
,('http://snomed.info/sct', '416714005', 'Episodic flashbacks (disorder)')
,('http://snomed.info/sct', '417143004', 'Short duration flashbacks (disorder)')
,('http://snomed.info/sct', '42344001', 'Psychosis caused by ingestible alcohol (disorder)')
,('http://snomed.info/sct', '425339005', 'Barbiturate withdrawal (disorder)')
,('http://snomed.info/sct', '425885002', 'Continuous phencyclidine abuse (disorder)')
,('http://snomed.info/sct', '426001001', 'Fentanyl dependence (disorder)')
,('http://snomed.info/sct', '426095000', 'Continuous inhalant abuse (disorder)')
,('http://snomed.info/sct', '426873000', 'Methamphetamine dependence (disorder)')
,('http://snomed.info/sct', '427205009', 'Amphetamine abuse, continuous (disorder)')
,('http://snomed.info/sct', '427229002', 'Episodic inhalant abuse (disorder)')
,('http://snomed.info/sct', '427327003', 'Sedative dependence (disorder)')
,('http://snomed.info/sct', '428370001', 'Psychostimulant withdrawal (disorder)')
,('http://snomed.info/sct', '429692000', 'Amphetamine abuse, episodic (disorder)')
,('http://snomed.info/sct', '43497001', 'Amphetamine-induced mood disorder (disorder)')
,('http://snomed.info/sct', '441527004', 'Stimulant abuse (disorder)')
,('http://snomed.info/sct', '442406005', 'Stimulant dependence (disorder)')
,('http://snomed.info/sct', '46975003', 'Organic mental disorder caused by cocaine (disorder)')
,('http://snomed.info/sct', '47664006', 'Sedative, hypnotic AND/OR anxiolytic-induced psychotic disorder with hallucinations (disorder)')
,('http://snomed.info/sct', '5002000', 'Inhalant dependence (disorder)')
,('http://snomed.info/sct', '50320000', 'Hallucinogen intoxication (disorder)')
,('http://snomed.info/sct', '50933003', 'Hallucinogen delusional disorder (disorder)')
,('http://snomed.info/sct', '51443000', 'Amphetamine-induced psychotic disorder with hallucinations (disorder)')
,('http://snomed.info/sct', '51493001', 'Anxiety disorder caused by cocaine (disorder)')
,('http://snomed.info/sct', '520841000124109', 'Diamorphine abuse (disorder)')
,('http://snomed.info/sct', '52866005', 'Opioid intoxication delirium (disorder)')
,('http://snomed.info/sct', '53050002', 'Organic mental disorder caused by hallucinogen (disorder)')
,('http://snomed.info/sct', '53936005', 'Mood disorder caused by ingestible alcohol (disorder)')
,('http://snomed.info/sct', '5444000', 'Sedative, hypnotic AND/OR anxiolytic intoxication delirium (disorder)')
,('http://snomed.info/sct', '5602001', 'Opioid abuse (disorder)')
,('http://snomed.info/sct', '57588009', 'Sedative, hypnotic AND/OR anxiolytic-induced sleep disorder (disorder)')
,('http://snomed.info/sct', '58727001', 'Phencyclidine dependence (disorder)')
,('http://snomed.info/sct', '59651006', 'Sedative, hypnotic AND/OR anxiolytic-induced persisting dementia (disorder)')
,('http://snomed.info/sct', '61104008', 'Inhalant-induced organic mental disorder (disorder)')
,('http://snomed.info/sct', '61144001', 'Alcohol-induced psychotic disorder with delusions (disorder)')
,('http://snomed.info/sct', '6348008', 'Cocaine-induced psychotic disorder with hallucinations (disorder)')
,('http://snomed.info/sct', '63649001', 'Cannabis delusional disorder (disorder)')
,('http://snomed.info/sct', '63983005', 'Inhalant-induced psychotic disorder with hallucinations (disorder)')
,('http://snomed.info/sct', '64386003', 'Sedative abuse (disorder)')
,('http://snomed.info/sct', '66590003', 'Alcohol dependence (disorder)')
,('http://snomed.info/sct', '699449003', 'Methamphetamine abuse (disorder)')
,('http://snomed.info/sct', '70328006', 'Cocaine intoxication delirium (disorder)')
,('http://snomed.info/sct', '70340006', 'Inhalant abuse (disorder)')
,('http://snomed.info/sct', '703845008', 'Buprenorphine dependence (disorder)')
,('http://snomed.info/sct', '703846009', 'Buprenorphine withdrawal (disorder)')
,('http://snomed.info/sct', '703847000', 'Buprenorphine + naloxone withdrawal (disorder)')
,('http://snomed.info/sct', '703848005', 'Cannabis withdrawal (disorder)')
,('http://snomed.info/sct', '703849002', 'Benzodiazepine withdrawal (disorder)')
,('http://snomed.info/sct', '703850002', 'Delirium due to benzodiazepine withdrawal (disorder)')
,('http://snomed.info/sct', '7052005', 'Alcohol hallucinosis (disorder)')
,('http://snomed.info/sct', '70701004', 'Alcoholic amblyopia (disorder)')
,('http://snomed.info/sct', '7071007', 'Phencyclidine abuse (disorder)')
,('http://snomed.info/sct', '70932007', 'Sexual dysfunction caused by amfetamine (finding)')
,('http://snomed.info/sct', '71328000', 'Sexual dysfunction caused by opioid (finding)')
,('http://snomed.info/sct', '713583005', 'Mild alcohol dependence (disorder)')
,('http://snomed.info/sct', '713862009', 'Severe alcohol dependence (disorder)')
,('http://snomed.info/sct', '714829008', 'Moderate alcohol dependence (disorder)')
,('http://snomed.info/sct', '7200002', 'Alcoholism (disorder)')
,('http://snomed.info/sct', '723926008', 'Perceptual disturbances and seizures co-occurrent and due to alcohol withdrawal (disorder)')
,('http://snomed.info/sct', '723927004', 'Psychotic disorder caused by alcohol with schizophreniform symptoms (disorder)')
,('http://snomed.info/sct', '723928009', 'Mood disorder with depressive symptoms caused by alcohol (disorder)')
,('http://snomed.info/sct', '723929001', 'Mood disorder with manic symptoms caused by alcohol (disorder)')
,('http://snomed.info/sct', '723930006', 'Mood disorder with mixed manic and depressive symptoms caused by alcohol (disorder)')
,('http://snomed.info/sct', '723933008', 'Cannabis dependence with current use (disorder)')
,('http://snomed.info/sct', '723936000', 'Psychotic disorder caused by cannabis (disorder)')
,('http://snomed.info/sct', '723937009', 'Sleep disorder caused by cannabis (disorder)')
,('http://snomed.info/sct', '724653003', 'Opioid dependence with current use (disorder)')
,('http://snomed.info/sct', '724655005', 'Psychotic disorder caused by opioid (disorder)')
,('http://snomed.info/sct', '724656006', 'Hypnotic dependence (disorder)')
,('http://snomed.info/sct', '724657002', 'Sedative dependence with current use (disorder)')
,('http://snomed.info/sct', '724658007', 'Hypnotic dependence with current use (disorder)')
,('http://snomed.info/sct', '724659004', 'Anxiolytic dependence with current use (disorder)')
,('http://snomed.info/sct', '724660009', 'Hypnotic withdrawal (disorder)')
,('http://snomed.info/sct', '724661008', 'Anxiolytic withdrawal (disorder)')
,('http://snomed.info/sct', '724662001', 'Sedative withdrawal without complication (disorder)')
,('http://snomed.info/sct', '724663006', 'Hypnotic withdrawal without complication (disorder)')
,('http://snomed.info/sct', '724664000', 'Anxiolytic withdrawal without complication (disorder)')
,('http://snomed.info/sct', '724665004', 'Perceptual disturbances co-occurrent and due to sedative withdrawal (disorder)')
,('http://snomed.info/sct', '724666003', 'Perceptual disturbances co-occurrent and due to hypnotic withdrawal (disorder)')
,('http://snomed.info/sct', '724667007', 'Perceptual disturbances co-occurrent and due to anxiolytic withdrawal (disorder)')
,('http://snomed.info/sct', '724668002', 'Seizure co-occurrent and due to sedative withdrawal (disorder)')
,('http://snomed.info/sct', '724669005', 'Seizure co-occurrent and due to hypnotic withdrawal (disorder)')
,('http://snomed.info/sct', '724670006', 'Seizure co-occurrent and due to anxiolytic withdrawal (disorder)')
,('http://snomed.info/sct', '724671005', 'Perceptual disturbances and seizures co-occurrent and due to sedative withdrawal (disorder)')
,('http://snomed.info/sct', '724672003', 'Perceptual disturbances and seizures co-occurrent and due to hypnotic withdrawal (disorder)')
,('http://snomed.info/sct', '724675001', 'Psychotic disorder caused by anxiolytic (disorder)')
,('http://snomed.info/sct', '724688003', 'Cocaine dependence with current use (disorder)')
,('http://snomed.info/sct', '724689006', 'Psychotic disorder caused by cocaine (disorder)')
,('http://snomed.info/sct', '724690002', 'Mood disorder with depressive symptoms caused by cocaine (disorder)')
,('http://snomed.info/sct', '724691003', 'Mood disorder with manic symptoms caused by cocaine (disorder)')
,('http://snomed.info/sct', '724692005', 'Mood disorder with mixed depressive and manic symptoms caused by cocaine (disorder)')
,('http://snomed.info/sct', '724693000', 'Obsessive compulsive disorder caused by cocaine (disorder)')
,('http://snomed.info/sct', '724695007', 'Hallucinogen dependence with current use (disorder)')
,('http://snomed.info/sct', '724696008', 'Psychotic disorder caused by hallucinogen (disorder)')
,('http://snomed.info/sct', '724700000', 'Volatile inhalant dependence with current use (disorder)')
,('http://snomed.info/sct', '724701001', 'Volatile inhalant withdrawal (disorder)')
,('http://snomed.info/sct', '724702008', 'Psychotic disorder caused by volatile inhalant (disorder)')
,('http://snomed.info/sct', '724704009', 'Methylenedioxymethamphetamine dependence with current use (disorder)')
,('http://snomed.info/sct', '724706006', 'Psychotic disorder caused by methylenedioxymethamphetamine (disorder)')
,('http://snomed.info/sct', '724712001', 'Harmful use of dissociative drug (disorder)')
,('http://snomed.info/sct', '724713006', 'Harmful use of ketamine (disorder)')
,('http://snomed.info/sct', '724714000', 'Dependence caused by dissociative substance (disorder)')
,('http://snomed.info/sct', '724715004', 'Dependence caused by ketamine (disorder)')
,('http://snomed.info/sct', '724720004', 'Mood disorder caused by dissociative drug (disorder)')
,('http://snomed.info/sct', '724724008', 'Psychoactive substance dependence with current use (disorder)')
,('http://snomed.info/sct', '724725009', 'Psychoactive substance withdrawal without complication (disorder)')
,('http://snomed.info/sct', '724726005', 'Perceptual disturbances co-occurrent and due to psychoactive substance withdrawal (disorder)')
,('http://snomed.info/sct', '724727001', 'Seizure co-occurrent and due to psychoactive substance withdrawal (disorder)')
,('http://snomed.info/sct', '724728006', 'Perceptual disturbances and seizures co-occurrent and due to psychoactive substance withdrawal (disorder)')
,('http://snomed.info/sct', '724732000', 'Sleep disorder caused by psychoactive substance (disorder)')
,('http://snomed.info/sct', '73097000', 'Alcohol amnestic disorder (disorder)')
,('http://snomed.info/sct', '735750005', 'Psychotic disorder with schizophreniform symptoms caused by cocaine (disorder)')
,('http://snomed.info/sct', '737338002', 'Synthetic cannabinoid withdrawal (disorder)')
,('http://snomed.info/sct', '74851005', 'Hallucinogen abuse (disorder)')
,('http://snomed.info/sct', '74934004', 'Psychoactive substance-induced withdrawal syndrome (disorder)')
,('http://snomed.info/sct', '75122001', 'Inhalant-induced psychotic disorder with delusions (disorder)')
,('http://snomed.info/sct', '75544000', 'Opioid dependence (disorder)')
,('http://snomed.info/sct', '762320004', 'Mood disorder with manic symptoms caused by opioid (disorder)')
,('http://snomed.info/sct', '762321000', 'Mood disorder with depressive symptoms caused by opioid (disorder)')
,('http://snomed.info/sct', '762322007', 'Mood disorder with mixed depressive and manic symptoms caused by opioid (disorder)')
,('http://snomed.info/sct', '762324008', 'Delirium caused by stimulant (disorder)')
,('http://snomed.info/sct', '762325009', 'Psychotic disorder caused by stimulant (disorder)')
,('http://snomed.info/sct', '762326005', 'Psychotic disorder with hallucinations caused by stimulant (disorder)')
,('http://snomed.info/sct', '762327001', 'Psychotic disorder with delusions caused by stimulant (disorder)')
,('http://snomed.info/sct', '762333005', 'Sexual dysfunction caused by stimulant (disorder)')
,('http://snomed.info/sct', '762334004', 'Sleep disorder caused by stimulant (disorder)')
,('http://snomed.info/sct', '762335003', 'Mood disorder with manic symptoms caused by hallucinogen (disorder)')
,('http://snomed.info/sct', '762336002', 'Mood disorder with depressive symptoms caused by hallucinogen (disorder)')
,('http://snomed.info/sct', '762337006', 'Mood disorder with mixed depressive and manic symptoms caused by hallucinogen (disorder)')
,('http://snomed.info/sct', '762338001', 'Mood disorder with manic symptoms caused by volatile inhalant (disorder)')
,('http://snomed.info/sct', '762339009', 'Mood disorder with depressive symptoms caused by volatile inhalant (disorder)')
,('http://snomed.info/sct', '762340006', 'Mood disorder with mixed depressive and manic symptoms caused by volatile inhalant (disorder)')
,('http://snomed.info/sct', '762344002', 'Mood disorder with manic symptoms caused by dissociative drug (disorder)')
,('http://snomed.info/sct', '762345001', 'Mood disorder with depressive symptoms caused by dissociative drug (disorder)')
,('http://snomed.info/sct', '762346000', 'Mood disorder with mixed depressive and manic symptoms caused by dissociative drug (disorder)')
,('http://snomed.info/sct', '762504005', 'Abuse of synthetic cathinone (disorder)')
,('http://snomed.info/sct', '762505006', 'Synthetic cathinone dependence (disorder)')
,('http://snomed.info/sct', '762517008', 'Sexual dysfunction caused by synthetic cathinone (disorder)')
,('http://snomed.info/sct', '762672001', 'Synthetic cathinone withdrawal (disorder)')
,('http://snomed.info/sct', '77355000', 'Organic mental disorder caused by cannabis (disorder)')
,('http://snomed.info/sct', '78267003', 'Cocaine abuse (disorder)')
,('http://snomed.info/sct', '78358001', 'Amphetamine withdrawal (disorder)')
,('http://snomed.info/sct', '785277001', 'Harmful pattern of use of amfetamine and/or amfetamine derivative (disorder)')
,('http://snomed.info/sct', '80868005', 'Cocaine withdrawal (disorder)')
,('http://snomed.info/sct', '817962007', 'Chlordiazepoxide dependence (disorder)')
,('http://snomed.info/sct', '82339009', 'Anxiety disorder caused by amfetamine (disorder)')
,('http://snomed.info/sct', '83367009', 'Organic mental disorder caused by amphetamine and/or amfetamine derivative (disorder)')
,('http://snomed.info/sct', '838527002', 'Amfetamine and/or amfetamine derivative drug dependence (disorder)')
,('http://snomed.info/sct', '84758004', 'Amphetamine abuse (disorder)')
,('http://snomed.info/sct', '85005007', 'Cannabis dependence (disorder)')
,('http://snomed.info/sct', '85561006', 'Uncomplicated alcohol withdrawal (disorder)')
,('http://snomed.info/sct', '86325007', 'Non megaloblastic anemia due to alcoholism (disorder)')
,('http://snomed.info/sct', '8635005', 'Alcohol withdrawal delirium (disorder)')
,('http://snomed.info/sct', '86391000119101', 'Inhalant dependence, continuous (disorder)')
,('http://snomed.info/sct', '86401000119104', 'Inhalant dependence, episodic (disorder)')
,('http://snomed.info/sct', '87132004', 'Opioid withdrawal (disorder)')
,('http://snomed.info/sct', '87810006', 'Megaloblastic anemia due to alcoholism (disorder)')
,('http://snomed.info/sct', '8837000', 'Delirium caused by amphetamine (disorder)')
,('http://snomed.info/sct', '88926005', 'Opioid-induced sleep disorder (disorder)')
,('http://snomed.info/sct', '89451009', 'Inhalant-induced mood disorder (disorder)')
,('http://snomed.info/sct', '91388009', 'Psychoactive substance abuse (disorder)')
,('http://snomed.info/sct', '95661003', 'Ergotamine withdrawal (disorder)')
,('http://snomed.info/sct', '97571000119109', 'Thrombocytopenia co-occurrent and due to alcoholism (disorder)')
) AS t (system, code, display) ;