study_prefix = "opioid"

[table_builder_config]
file_names = [
    "vocab/static_builder.py",
    "vocab/rxnorm_vsac_builder.py",
    "vocab/additional_rules_builder.py",
]

# [sql_config]
# file_names = [
#     "define_dx.sql",
#     "define_dx_sepsis.sql",
#     "define_dx_sud.sql",
#     "define_lab.sql",
#     "define_rx.sql",
#     "define_rx_buprenorphine.sql",
#     "define_rx_naloxone.sql",
#     "define_rx_opioid.sql",
#     "table_study_period.sql",
#     "table_dx.sql",
#     "table_dx_sepsis.sql",
#     "table_lab.sql",
#     "table_rx.sql",
#     "version.sql"
# ]

# [counts_builder_config]
# file_names = [
#     "counts.py"
# ]


# [export_config]
# export_list = [
#     "opioid__count_study_period_week",
#     "opioid__count_study_period_month",
#     "opioid__count_dx_sepsis_week",
#     "opioid__count_dx_sepsis_month",
#     "opioid__count_dx_month",
#     "opioid__count_dx_week",
#     "opioid__count_lab_month",
#     "opioid__count_lab_week",
#     "opioid__count_medicationrequest",
#     "opioid__count_rx",
#     "opioid__count_rx_opioid",
#     "opioid__count_rx_buprenorphine",
#     "opioid__count_rx_naloxone",
#     "opioid__meta_version",
# ]
